Repository pmem/rpma, pull requests merged in 2020-10, with the labels that each got.

#500 rpma: write the 'MESSAGING' section of the librpma.7 manual
  src/include/librpma.h
Labels: sprint goal

#507 doc: add the missing documentation
  src/include/librpma.h
Labels: sprint goal

#512 common: unified files names
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-next_completion.c
  tests/unit/conn/conn-next_event.c
  tests/unit/conn/conn-prepare_completions.c
  tests/unit/conn/conn-private_data.c
Labels: sprint goal

#514 common: version number to include patch version always
  CMakeLists.txt
Labels: sprint goal

#508 doc: librpma.7: queues, performance and resource use
  src/include/librpma.h
Labels: sprint goal

#519 rpma: change names of completion API calls
  doc/manuals_3.txt
  examples/02-read-to-volatile/client.c
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/client.c
  examples/05-flush-to-persistent/client.c
  examples/06-multiple-connections/server.c
  examples/07-atomic-write/client.c
  examples/08-messages-ping-pong/client.c
  examples/08-messages-ping-pong/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  src/conn.c
  src/include/librpma.h
  src/librpma.map
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-completion_get.c
  tests/unit/conn/conn-completion_wait.c
Labels: sprint goal

#522 rpma: write the 'REMOTE MEMORY ACCESS' section of the librpma.7 manual
  src/include/librpma.h
Labels: sprint goal

#517 doc: librpma.7: thread safety
  src/include/librpma.h
Labels: sprint goal

#518 rpma: write the 'COMPLETIONS' section of the librpma.7 manual
  src/include/librpma.h
Labels: sprint goal

#521 rpma: write the 'PEER' section of the librpma.7 manual
  src/include/librpma.h
Labels: sprint goal

#524 rpma: write the 'ON-DEMAND PAGING SUPPORT' section of librpma.7 manual
  src/include/librpma.h
Labels: sprint goal

#539 common: enhance custom make targets
  CMakeLists.txt
  examples/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build system, enhancement

#544 examples: fix error: variable 'is_pmem' set but not used
  examples/09-flush-to-persistent-GPSPM/client.c
Labels: bug fix

#540 common: remove setting the nonexisting BUILD_BENCHMARKS variable
  utils/docker/run-doc-update.sh
Labels: bug fix, build system

#541 examples: fix setting unset variable STATE_OK
  examples/run-all-on-SoftRoCE.sh
Labels: bug fix

#538 common: generate documentation in the 'manpages' directory
  utils/docker/run-doc-update.sh
Labels: documentation, enhancement

#513 common: remove broken block for in-source builds
  CMakeLists.txt
Labels: bug fix, build system

#550 rpma: ibv_post_send and ibv_post_recv return errno
  src/mr.c
Labels: sprint goal

#551 rpma: abs(errno) because ibv_* likes to return -errno
  src/log_internal.h
Labels: sprint goal

#542 examples: add support for USB Ethernet network interfaces
  examples/config_softroce.sh
Labels: enhancement

#537 doc: add documentation for v0.9.0
  _data/releases_linux.yml
  index.md
  manpages/v0.9.0/librpma.7.md
  manpages/v0.9.0/rpma_conn_apply_remote_peer_cfg.3.md
  manpages/v0.9.0/rpma_conn_cfg_delete.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_cq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_rq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_sq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_timeout.3.md
  manpages/v0.9.0/rpma_conn_cfg_new.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_cq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_rq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_sq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_timeout.3.md
  manpages/v0.9.0/rpma_conn_completion_get.3.md
  manpages/v0.9.0/rpma_conn_completion_wait.3.md
  manpages/v0.9.0/rpma_conn_delete.3.md
  manpages/v0.9.0/rpma_conn_disconnect.3.md
  manpages/v0.9.0/rpma_conn_get_completion_fd.3.md
  manpages/v0.9.0/rpma_conn_get_event_fd.3.md
  manpages/v0.9.0/rpma_conn_get_private_data.3.md
  manpages/v0.9.0/rpma_conn_next_event.3.md
  manpages/v0.9.0/rpma_conn_req_connect.3.md
  manpages/v0.9.0/rpma_conn_req_delete.3.md
  manpages/v0.9.0/rpma_conn_req_new.3.md
  manpages/v0.9.0/rpma_conn_req_recv.3.md
  manpages/v0.9.0/rpma_ep_get_fd.3.md
  manpages/v0.9.0/rpma_ep_listen.3.md
  manpages/v0.9.0/rpma_ep_next_conn_req.3.md
  manpages/v0.9.0/rpma_ep_shutdown.3.md
  manpages/v0.9.0/rpma_err_2str.3.md
  manpages/v0.9.0/rpma_flush.3.md
  manpages/v0.9.0/rpma_log_get_threshold.3.md
  manpages/v0.9.0/rpma_log_set_function.3.md
  manpages/v0.9.0/rpma_log_set_threshold.3.md
  manpages/v0.9.0/rpma_mr_dereg.3.md
  manpages/v0.9.0/rpma_mr_get_descriptor.3.md
  manpages/v0.9.0/rpma_mr_get_descriptor_size.3.md
  manpages/v0.9.0/rpma_mr_reg.3.md
  manpages/v0.9.0/rpma_mr_remote_delete.3.md
  manpages/v0.9.0/rpma_mr_remote_from_descriptor.3.md
  manpages/v0.9.0/rpma_mr_remote_get_flush_type.3.md
  manpages/v0.9.0/rpma_mr_remote_get_size.3.md
  manpages/v0.9.0/rpma_peer_cfg_delete.3.md
  manpages/v0.9.0/rpma_peer_cfg_from_descriptor.3.md
  manpages/v0.9.0/rpma_peer_cfg_get_descriptor.3.md
  manpages/v0.9.0/rpma_peer_cfg_get_descriptor_size.3.md
  manpages/v0.9.0/rpma_peer_cfg_get_direct_write_to_pmem.3.md
  manpages/v0.9.0/rpma_peer_cfg_new.3.md
  manpages/v0.9.0/rpma_peer_cfg_set_direct_write_to_pmem.3.md
  manpages/v0.9.0/rpma_peer_delete.3.md
  manpages/v0.9.0/rpma_peer_new.3.md
  manpages/v0.9.0/rpma_read.3.md
  manpages/v0.9.0/rpma_recv.3.md
  manpages/v0.9.0/rpma_send.3.md
  manpages/v0.9.0/rpma_utils_conn_event_2str.3.md
  manpages/v0.9.0/rpma_utils_get_ibv_context.3.md
  manpages/v0.9.0/rpma_utils_ibv_context_is_odp_capable.3.md
  manpages/v0.9.0/rpma_write.3.md
  manpages/v0.9.0/rpma_write_atomic.3.md
Labels: documentation, sprint goal
