Repository pmem/rpma, pull requests merged in 2020-09, with the labels that each got.

#313 common: remove hardcoded timeout from info.c module
  src/conn_req.c
  src/conn_req.h
  src/include/librpma.h
  src/info.c
  src/info.h
  src/rpma.c
  tests/unit/common/mocks-rdma_cm.c
  tests/unit/common/mocks-rpma-info.c
  tests/unit/common/test-common.h
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-new.c
  tests/unit/info/info-resolve_addr.c
  tests/unit/utils/utils-common.c
Labels: sprint goal

#321 rpma: add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: sprint goal

#324 common: rpma_conn_cfg scaffolding
  examples/01-connection/client.c
  examples/01-connection/server.c
  examples/06-multiple-connections/server.c
  examples/common/common-conn.c
  src/CMakeLists.txt
  src/conn_cfg.c
  src/conn_cfg.h
  src/conn_req.c
  src/conn_req.h
  src/ep.c
  src/include/librpma.h
  src/librpma.map
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-from_cm_event.c
  tests/unit/conn_req/conn_req-new.c
  tests/unit/ep/ep-common.c
  tests/unit/ep/ep-next_conn_req.c
Labels: sprint goal

#326 rpma: implement rpma_conn_req_recv() and its unit tests
  src/conn_req.c
  tests/unit/common/test-common.h
  tests/unit/conn/conn-common.h
  tests/unit/conn_req/CMakeLists.txt
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-common.h
  tests/unit/conn_req/conn_req-recv.c
  tests/unit/peer/peer-common.h
Labels: sprint goal

#328 rpma: implement rpma_mr_recv() and its unit tests
  src/mr.c
  tests/unit/common/mocks-ibverbs.c
  tests/unit/common/mocks-ibverbs.h
  tests/unit/mr/CMakeLists.txt
  tests/unit/mr/mr-recv.c
Labels: sprint goal

#330 common: do not install and package sources of examples
  CMakeLists.txt
Labels: sprint goal

#318 examples: add atomic_write example
  examples/07-atomic-write/CMakeLists.txt
  examples/07-atomic-write/README.md
  examples/07-atomic-write/client.c
  examples/07-atomic-write/server.c
  examples/CMakeLists.txt
Labels: sprint goal

#333 examples: make sure the server's process is finished
  examples/run-all-on-SoftRoCE.sh
Labels: sprint goal

#334 exmaples: fix runnning 07-atomic-write example on SoftRoCE
  examples/run-all-on-SoftRoCE.sh
Labels: sprint goal

#336 examples: fix 07-atomic-write example on SoftRoCE
  examples/07-atomic-write/server.c
Labels: sprint goal

#335 common: handle RECV/SEND in _next_completion
  src/conn.c
  tests/unit/conn/conn-next-completion.c
Labels: sprint goal

#337 common: add conn_cfg to rpma_peer_create_qp
  src/conn_req.c
  src/peer.c
  src/peer.h
  tests/unit/common/mocks-rpma-peer.c
  tests/unit/peer/peer-create_qp.c
Labels: sprint goal

#341 examples: fix arguments of 08-messages-ping-pong example on SoftRoCE
  examples/run-all-on-SoftRoCE.sh
Labels: sprint goal

#331 common: conn_cfg module implementation and tests
  src/conn_cfg.c
  src/conn_cfg.h
  src/include/librpma.h
  tests/unit/CMakeLists.txt
  tests/unit/common/test-common.h
  tests/unit/conn_cfg/CMakeLists.txt
  tests/unit/conn_cfg/conn_cfg-common.c
  tests/unit/conn_cfg/conn_cfg-common.h
  tests/unit/conn_cfg/conn_cfg-cq_size.c
  tests/unit/conn_cfg/conn_cfg-cqe.c
  tests/unit/conn_cfg/conn_cfg-delete.c
  tests/unit/conn_cfg/conn_cfg-new.c
  tests/unit/conn_cfg/conn_cfg-rq_size.c
  tests/unit/conn_cfg/conn_cfg-sq_size.c
  tests/unit/conn_cfg/conn_cfg-timeout.c
Labels: sprint goal

#338 common: pass conn_cfg via ep_next_conn_req()
  src/ep.c
  tests/integration/example-01-connection/CMakeLists.txt
  tests/integration/example-02-read-to-volatile/CMakeLists.txt
  tests/unit/common/mocks-rpma-conn_cfg.c
  tests/unit/common/mocks-rpma-conn_cfg.h
  tests/unit/common/test-common.h
  tests/unit/ep/CMakeLists.txt
  tests/unit/ep/ep-common.c
  tests/unit/ep/ep-common.h
  tests/unit/ep/ep-get_fd.c
  tests/unit/ep/ep-listen.c
  tests/unit/ep/ep-next_conn_req.c
Labels: sprint goal

#332 doc: fix installing and packaging manuals
  doc/CMakeLists.txt
  doc/manuals_3.txt
  doc/manuals_7.txt
  utils/src2mans.sh
Labels: sprint goal

#343 examples: fix error: macro "LOG_HDR_SIGNATURE" is not used
  examples/07-atomic-write/server.c
Labels: sprint goal

#339 common: pass conn_cfg via conn_req_new/_from_cm_event()
  src/conn_req.c
  tests/integration/common/mocks.c
  tests/unit/common/mocks-ibverbs.c
  tests/unit/common/mocks-rdma_cm.c
  tests/unit/common/mocks-rpma-conn_cfg.c
  tests/unit/common/mocks-rpma-conn_cfg.h
  tests/unit/common/mocks-rpma-peer.c
  tests/unit/conn_req/CMakeLists.txt
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-common.h
  tests/unit/conn_req/conn_req-connect.c
  tests/unit/conn_req/conn_req-delete.c
  tests/unit/conn_req/conn_req-from_cm_event.c
  tests/unit/conn_req/conn_req-new.c
  tests/unit/conn_req/conn_req-recv.c
Labels: sprint goal

#340 common: pass conn_cfg via peer_create_qp()
  src/conn_req.h
  src/peer.c
  tests/unit/common/mocks-rpma-conn_cfg.c
  tests/unit/common/mocks-rpma-conn_cfg.h
  tests/unit/peer/CMakeLists.txt
  tests/unit/peer/peer-create_qp.c
Labels: sprint goal

#357 rpma: check if memory is allocated (rpma_flush_apm)
  src/flush.c
  tests/unit/flush/flush-new.c
Labels: sprint goal

#361 common: fix librpma pkg-config file
  cmake/librpma.pc.in
Labels: sprint goal

#367 test: add the missing test case
  tests/unit/mr/mr-reg.c
Labels: sprint goal

#370 rpma: peer_cfg scaffolding
  doc/manuals_3.txt
  src/CMakeLists.txt
  src/conn.c
  src/include/librpma.h
  src/librpma.map
  src/peer_cfg.c
  src/peer_cfg.h
Labels: sprint goal

#354 examples: fix numeric overflow
  examples/06-multiple-connections/server.c
Labels: sprint goal

#345 common: find libibverbs and librdmacm w/o PkgConfig
  CMakeLists.txt
  cmake/FindLIBIBVERBS.cmake
  cmake/FindLIBRDMACM.cmake
  cmake/packages.cmake
  examples/01-connection/CMakeLists.txt
  examples/02-read-to-volatile/CMakeLists.txt
  examples/03-read-to-persistent/CMakeLists.txt
  examples/04-write-to-persistent/CMakeLists.txt
  examples/05-flush-to-persistent/CMakeLists.txt
  examples/06-multiple-connections/CMakeLists.txt
  examples/07-atomic-write/CMakeLists.txt
  examples/08-messages-ping-pong/CMakeLists.txt
  examples/cmake/FindLIBRPMA.cmake
  examples/template-example/CMakeLists.txt
Labels: sprint goal

#368 common: remove *_REQUIRED_VERSION for libibverbs and librdmacm
  CMakeLists.txt
  cmake/packages.cmake
  examples/08-messages-ping-pong/CMakeLists.txt
Labels: sprint goal

#363 common: check if libibverbs has ODP support
  CMakeLists.txt
  cmake/functions.cmake
Labels: sprint goal

#380 rpma: fix return value of rpma_mr_remote_from_descriptor()
  src/mr.c
  tests/unit/mr/mr-descriptor.c
Labels: sprint goal

#381 doc: update and cleanup
  _data/libs_map.yml
  _data/releases_linux.yml
Labels: sprint goal

#371 examples: fix non null terminated string
  examples/06-multiple-connections/client.c
Labels: sprint goal

#382 examples: add peer_desc to the common_data structure
  examples/03-read-to-persistent/client.c
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/client.c
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/07-atomic-write/client.c
  examples/07-atomic-write/server.c
  examples/common/common-conn.h
Labels: sprint goal

#369 common: check if librdmacm has correct signature of rdma_getaddrinfo()
  CMakeLists.txt
  cmake/functions.cmake
Labels: sprint goal

#386 rpma: fix 'store to misaligned address' errors in serializing data
  src/mr.c
Labels: bug fix, sprint goal

#309 common: add a build with ASAN and UBSAN turned on
  utils/docker/run-build.sh
Labels: enhancement, sprint goal

#379 doc: fix checking if pandoc can be found
  doc/CMakeLists.txt
  utils/src2mans.sh
Labels: bug fix

#378 rpma: implement rpma_peer_cfg
  doc/manuals_3.txt
  src/include/librpma.h
  src/librpma.map
  src/peer_cfg.c
  tests/unit/CMakeLists.txt
  tests/unit/peer_cfg/CMakeLists.txt
  tests/unit/peer_cfg/peer_cfg-common.c
  tests/unit/peer_cfg/peer_cfg-common.h
  tests/unit/peer_cfg/peer_cfg-delete.c
  tests/unit/peer_cfg/peer_cfg-descriptor.c
  tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c
  tests/unit/peer_cfg/peer_cfg-new.c
Labels: sprint goal

#384 examples: incorporate peer's configuration
  examples/05-flush-to-persistent/README.md
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/07-atomic-write/README.md
  examples/07-atomic-write/client.c
Labels: sprint goal

#394 examples: fix defining ON_STR
  examples/05-flush-to-persistent/server.c
Labels: bug fix

#396 examples: fix error handling in examples/07-atomic-write/client.c
  examples/07-atomic-write/client.c
Labels: bug fix

#383 common: fix installing txt2man in /usr
  utils/docker/images/install-txt2man.sh
Labels: bug fix

#392 common: add libprotobuf-c-dev(el) to docker images
  utils/docker/images/Dockerfile.fedora-31
  utils/docker/images/Dockerfile.ubuntu-19.10
Labels: sprint goal

#365 common: require Perl v5.10 instead of v5.16
  tests/match
  utils/check_whitespace
Labels: enhancement

#387 common: remove redundant 'make doc' test
  utils/docker/run-build.sh
Labels: enhancement

#397 common: remove the launch of interactive bash added for debugging
  utils/docker/run-build.sh
Labels: bug fix

#407 rpma: remove rpma_peer_cfg_descriptor
  doc/manuals_3.txt
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/common/common-conn.h
  src/include/librpma.h
  src/librpma.map
  src/peer_cfg.c
  tests/unit/peer_cfg/peer_cfg-common.h
  tests/unit/peer_cfg/peer_cfg-descriptor.c
Labels: sprint goal

#402 common: fix running check-ms-license.pl in check-headers.sh ultimately
  utils/check_license/check-headers.sh
Labels: bug fix, build system

#399 doc: rename peer_cfg get/set functions
  _data/libs_map.yml
  _data/releases_linux.yml
Labels: sprint goal

#391 common: check for package generators
  cmake/packages.cmake
Labels: bug fix

#388 test: fix creating the descriptor in example-02-read-to-volatile
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
Labels: bug fix

#401 rpma: implement rpma_conn_apply_remote_peer_cfg()
  src/conn.c
  src/include/librpma.h
  tests/integration/example-01-connection/CMakeLists.txt
  tests/integration/example-02-read-to-volatile/CMakeLists.txt
  tests/unit/common/mocks-rpma-peer_cfg.c
  tests/unit/common/test-common.h
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-apply_remote_peer_cfg.c
  tests/unit/conn/conn-common.h
  tests/unit/conn/conn-flush.c
  tests/unit/peer_cfg/peer_cfg-common.h
Labels: sprint goal

#390 doc: check if src2man, find and diff are installed
  INSTALL.md
  doc/CMakeLists.txt
Labels: bug fix, build system, sprint goal

#385 common: add examples/09-flush-to-persistent-GPSPM
  CMakeLists.txt
  INSTALL.md
  examples/09-flush-to-persistent-GPSPM/CMakeLists.txt
  examples/09-flush-to-persistent-GPSPM/GPSPM_flush.pb-c.c
  examples/09-flush-to-persistent-GPSPM/GPSPM_flush.pb-c.h
  examples/09-flush-to-persistent-GPSPM/GPSPM_flush.proto
  examples/09-flush-to-persistent-GPSPM/README.md
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/flush-to-persistent-GPSPM.h
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/CMakeLists.txt
Labels: sprint goal

#403 common: roadmap updated after demo on 9/3/2020
  ROADMAP.md
Labels: sprint goal

#395 common: fix checking signature of rdma_getaddrinfo()
  cmake/functions.cmake
Labels: bug fix, build system, sprint goal

#409 common: handle old signature of rdma_getaddrinfo()
  CMakeLists.txt
  cmake/functions.cmake
  src/info.c
  tests/integration/common/mocks.c
  tests/unit/common/mocks-rdma_cm.c
Labels: enhancement

#404 rpma: remove rpma_mr_descriptor structure
  doc/manuals_3.txt
  examples/02-read-to-volatile/client.c
  examples/02-read-to-volatile/server.c
  examples/03-read-to-persistent/client.c
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/client.c
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/06-multiple-connections/client.c
  examples/06-multiple-connections/server.c
  examples/07-atomic-write/client.c
  examples/07-atomic-write/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/common/common-conn.h
  src/include/librpma.h
  src/librpma.map
  src/mr.c
  tests/integration/common/mocks.h
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
  tests/unit/mr/mr-common.c
  tests/unit/mr/mr-common.h
  tests/unit/mr/mr-descriptor.c
Labels: sprint goal

#425 common: add const to all peer related API calls
  examples/common/common-conn.c
  examples/common/common-conn.h
  src/conn.c
  src/conn.h
  src/conn_req.c
  src/conn_req.h
  src/ep.c
  src/flush.c
  src/flush.h
  src/include/librpma.h
  src/mr.c
  src/peer.c
  src/peer.h
  tests/unit/common/mocks-rpma-conn.c
  tests/unit/common/mocks-rpma-flush.c
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/common/mocks-rpma-peer.c
  tests/unit/ep/ep-common.c
  tests/unit/peer/peer-create_qp.c
  tests/unit/peer/peer-mr_reg.c
Labels: sprint goal

#433 rpma: move librpma_log.h into librpma.h
  examples/01-connection/client.c
  examples/01-connection/server.c
  examples/02-read-to-volatile/client.c
  examples/02-read-to-volatile/server.c
  examples/03-read-to-persistent/client.c
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/client.c
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/06-multiple-connections/client.c
  examples/06-multiple-connections/server.c
  examples/07-atomic-write/client.c
  examples/07-atomic-write/server.c
  examples/08-messages-ping-pong/client.c
  examples/08-messages-ping-pong/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/log/log-example.c
  src/CMakeLists.txt
  src/include/librpma.h
  src/include/librpma_log.h
  src/log_default.h
  src/log_internal.h
Labels: sprint goal

#437 rpma: fix generating rpma_log_set_threshold.3.md by 'make doc'
  src/include/librpma.h
Labels: bug fix, sprint goal

#438 common: do not ignore errors of src2man
  utils/src2mans.sh
Labels: bug fix, sprint goal

#423 common: disable On-Demand Paging (ODP) if it is not supported
  CMakeLists.txt
  examples/01-connection/client.c
  examples/01-connection/server.c
  examples/02-read-to-volatile/client.c
  examples/02-read-to-volatile/server.c
  examples/common/common-conn.c
  examples/common/common-conn.h
  src/peer.c
  src/private_data.c
  src/rpma.c
  tests/integration/common/mocks.c
  tests/integration/common/mocks.h
  tests/integration/example-01-connection/example-01-connection.c
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
  tests/unit/common/mocks-ibverbs.c
  tests/unit/common/mocks-ibverbs.h
  tests/unit/common/test-common.h
  tests/unit/conn/conn-common.c
  tests/unit/conn/conn-next-completion.c
  tests/unit/info/info-bind_addr.c
  tests/unit/info/info-common.c
  tests/unit/info/info-resolve_addr.c
  tests/unit/peer/peer-mr_reg.c
  tests/unit/private_data/private_data-common.h
  tests/unit/utils/CMakeLists.txt
Labels: enhancement, sprint goal

#424 examples: workaround list(FILTER) from CMake >= v3.6
  examples/CMakeLists.txt
Labels: bug fix

#413 common: add missing FindLIBPROTOBUFC.cmake
  cmake/FindLIBPROTOBUFC.cmake
Labels: bug fix, sprint goal

#406 common: print out the 'common' area in nothing else was printed
  utils/check-area.sh
Labels: bug fix, build system

#412 examples: fix memory leak
  examples/09-flush-to-persistent-GPSPM/server.c
Labels: sprint goal

#420 doc: improve the documentation to rpma_peer... functions
  src/include/librpma.h
Labels: sprint goal

#422 rpma: remove memory placement from rpma_mr_reg()
  doc/manuals_3.txt
  examples/02-read-to-volatile/client.c
  examples/02-read-to-volatile/server.c
  examples/03-read-to-persistent/client.c
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/client.c
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/06-multiple-connections/client.c
  examples/06-multiple-connections/server.c
  examples/07-atomic-write/client.c
  examples/07-atomic-write/server.c
  examples/08-messages-ping-pong/client.c
  examples/08-messages-ping-pong/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  src/conn.c
  src/flush.c
  src/include/librpma.h
  src/librpma.map
  src/mr.c
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/conn/conn-flush.c
  tests/unit/mr/mr-common.c
  tests/unit/mr/mr-common.h
  tests/unit/mr/mr-descriptor.c
  tests/unit/mr/mr-reg.c
Labels: sprint goal

#421 common: skip example 09 if libprotobuf-c is missing
  utils/docker/run-build.sh
Labels: bug fix, sprint goal

#444 test: add missing unit tests for conn-flush
  tests/unit/conn/conn-flush.c
Labels: sprint goal

#446 rpma: replace enum typedefs with just enums
  src/include/librpma.h
  src/log.c
  src/log_default.c
  src/log_default.h
  src/log_internal.h
  tests/unit/common/mocks-rpma-log.c
  tests/unit/common/mocks-rpma-log_default.c
  tests/unit/log/macros.c
  tests/unit/log/threshold.c
  tests/unit/log_default/function.c
Labels: sprint goal

#445 test: add missing unit tests for rpma_mr_remote_get_flush_type()
  tests/unit/mr/CMakeLists.txt
  tests/unit/mr/mr-common.h
  tests/unit/mr/mr-get_flush_type.c
Labels: sprint goal

#439 add const to all possible API calls
  src/conn.c
  src/conn_cfg.c
  src/conn_cfg.h
  src/conn_req.c
  src/conn_req.h
  src/ep.c
  src/flush.c
  src/flush.h
  src/include/librpma.h
  src/mr.c
  src/mr.h
  src/peer.c
  src/peer.h
  src/peer_cfg.c
  tests/unit/common/mocks-rpma-conn_cfg.c
  tests/unit/common/mocks-rpma-flush.c
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/common/mocks-rpma-peer.c
  tests/unit/common/mocks-rpma-peer_cfg.c
  tests/unit/ep/ep-common.c
Labels: sprint goal

#426 doc: improve the documentation to rpma_mr... functions
  src/include/librpma.h
Labels: sprint goal

#428 doc: improve the documentation to rpma_conn... functions
  src/include/librpma.h
Labels: sprint goal

#429 doc: improve the documentation to rpma_ep... functions
  src/include/librpma.h
Labels: sprint goal

#431 doc: improve the documentation to rpma...completion functions
  src/include/librpma.h
Labels: sprint goal

#440 examples: link with -lrt for clock_gettime() for glibc < v2.17
  cmake/functions.cmake
  examples/01-connection/CMakeLists.txt
  examples/02-read-to-volatile/CMakeLists.txt
  examples/03-read-to-persistent/CMakeLists.txt
  examples/04-write-to-persistent/CMakeLists.txt
  examples/05-flush-to-persistent/CMakeLists.txt
  examples/06-multiple-connections/CMakeLists.txt
  examples/07-atomic-write/CMakeLists.txt
  examples/08-messages-ping-pong/CMakeLists.txt
  examples/09-flush-to-persistent-GPSPM/CMakeLists.txt
  examples/CMakeLists.txt
  examples/template-example/CMakeLists.txt
Labels: enhancement

#430 doc: improve the documentation to rpma... functions
  src/include/librpma.h
Labels: sprint goal

#455 common: fix setting TEST_DIR in run-build.sh
  utils/docker/run-build.sh
Labels: bug fix, build system

#432 doc: improve the documentation to rpma_err... functions
  src/include/librpma.h
Labels: sprint goal

#459 common: do not print the current directory in compile_example_standalone()
  utils/docker/run-build.sh
Labels: bug fix, sprint goal

#456 common: all pointers to a pointer should have _ptr suffix
  src/conn_req.c
  src/ep.c
  src/include/librpma.h
  src/info.h
  src/peer.c
  src/peer.h
  src/rpma.c
  tests/unit/common/mocks-rpma-peer.c
Labels: sprint goal

#461 common: fix all "message(NOTICE)" with "message(STATUS)"
  CMakeLists.txt
  cmake/functions.cmake
  examples/CMakeLists.txt
Labels: bug fix, sprint goal

#460 common: set sanitizer and coverage flags only in the main CMake file
  CMakeLists.txt
  cmake/functions.cmake
  examples/CMakeLists.txt
  tests/CMakeLists.txt
Labels: bug fix, sprint goal

#458 common: fix 'initialize' with 'initiate' where needed
  examples/01-connection/README.md
  examples/06-multiple-connections/server.c
  src/conn.c
  src/conn_req.c
  src/include/librpma.h
Labels: sprint goal

#366 common: add info about supported OSes to INSTALL.md
  INSTALL.md
Labels: enhancement

#398 common: fix handling PACKAGE_MANAGER in run-build.sh
  utils/docker/run-build.sh
Labels: bug fix, build system

#464 remove and hide functions from the rpma_err module
  doc/manuals_3.txt
  src/include/librpma.h
  src/librpma.map
  src/rpma_err.c
  src/rpma_err.h
  tests/unit/conn/conn-disconnect.c
  tests/unit/conn/conn-new.c
  tests/unit/conn/conn-next-completion.c
  tests/unit/conn/conn-next-event.c
  tests/unit/conn/conn-prepare-completions.c
  tests/unit/conn_req/conn_req-connect.c
  tests/unit/conn_req/conn_req-delete.c
  tests/unit/conn_req/conn_req-from_cm_event.c
  tests/unit/conn_req/conn_req-new.c
  tests/unit/ep/ep-listen.c
  tests/unit/ep/ep-next_conn_req.c
  tests/unit/error/error.c
  tests/unit/flush/flush-new.c
  tests/unit/info/info-bind_addr.c
  tests/unit/info/info-new.c
  tests/unit/info/info-resolve_addr.c
  tests/unit/mr/mr-reg.c
  tests/unit/peer/peer-create_qp.c
  tests/unit/peer/peer-mr_reg.c
  tests/unit/peer/peer-new.c
  tests/unit/utils/utils-ibv_context_is_odp_capable.c
Labels: sprint goal

#465 common: add missing cases to rpma_err_2str() + replace RPMA_E_NO_NEXT with RPMA_E_NO_EVENT
  examples/06-multiple-connections/server.c
  src/conn.c
  src/ep.c
  src/include/librpma.h
  src/rpma_err.c
  tests/unit/conn/conn-next-event.c
  tests/unit/ep/ep-next_conn_req.c
  tests/unit/error/error.c
Labels: bug fix, sprint goal

#466 examples: fix syntax in README.md of the 05 example
  examples/05-flush-to-persistent/README.md
Labels: bug fix, sprint goal

#467 examples: rename README to README.md and reword/reformat
  examples/README.md
  examples/template-example/README
  examples/template-example/README.md
Labels: bug fix, sprint goal

#469 common: add uninstalling installed librpma development packages
  utils/docker/run-build.sh
Labels: enhancement, sprint goal

#471 common: 0.9.0-rc1 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#473 common: add pandoc package to Ubuntu 19.10 Docker image
  utils/docker/images/Dockerfile.fedora-31
  utils/docker/images/Dockerfile.ubuntu-19.10
Labels: bug fix, build system

#472 common: move coverage build from Travis to GHA
  .github/workflows/gha.yml
  .travis.yml
  utils/docker/build.sh
  utils/docker/images/download-scripts.sh
Labels: build system, enhancement

#474 rpma: librpma 7 man page scaffolding
  src/include/librpma.h
Labels: documentation, sprint goal

#476 rpma: improve error logging
  src/conn.c
  tests/unit/common/mocks-rdma_cm.c
Labels: sprint goal

#477 rpma: remove provider error
  src/conn.c
  src/conn_req.c
  src/ep.c
  src/flush.c
  src/info.c
  src/mr.c
  src/peer.c
  src/peer_cfg.c
  src/rpma.c
  src/rpma_err.c
  src/rpma_err.h
  tests/unit/common/mocks-rpma-conn.c
  tests/unit/common/mocks-rpma-flush.c
  tests/unit/common/mocks-rpma-info.c
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/common/mocks-rpma-peer.c
  tests/unit/common/mocks-rpma-utils.c
  tests/unit/conn/conn-disconnect.c
  tests/unit/conn/conn-new.c
  tests/unit/conn/conn-next-completion.c
  tests/unit/conn/conn-next-event.c
  tests/unit/conn/conn-prepare-completions.c
  tests/unit/conn_req/conn_req-connect.c
  tests/unit/conn_req/conn_req-delete.c
  tests/unit/conn_req/conn_req-from_cm_event.c
  tests/unit/conn_req/conn_req-new.c
  tests/unit/ep/ep-common.c
  tests/unit/ep/ep-listen.c
  tests/unit/ep/ep-next_conn_req.c
  tests/unit/error/error.c
  tests/unit/flush/flush-new.c
  tests/unit/info/info-bind_addr.c
  tests/unit/info/info-new.c
  tests/unit/info/info-resolve_addr.c
  tests/unit/mr/mr-common.h
  tests/unit/mr/mr-read.c
  tests/unit/mr/mr-recv.c
  tests/unit/mr/mr-reg.c
  tests/unit/mr/mr-send.c
  tests/unit/mr/mr-write.c
  tests/unit/peer/peer-create_qp.c
  tests/unit/peer/peer-mr_reg.c
  tests/unit/peer/peer-new.c
  tests/unit/utils/utils-common.c
  tests/unit/utils/utils-get_ibv_context.c
  tests/unit/utils/utils-ibv_context_is_odp_capable.c
Labels: sprint goal

#481 rpma: remove conditions
  src/info.c
  tests/unit/info/info-resolve_addr.c
Labels: sprint goal

#483 rpma: improve comments
  src/peer.c
  tests/unit/mr/mr-descriptor.c
Labels: sprint goal

#482 rpma: remove const where related RDMA resources might be modified
  examples/common/common-conn.c
  examples/common/common-conn.h
  src/conn.c
  src/conn.h
  src/conn_req.c
  src/conn_req.h
  src/ep.c
  src/flush.c
  src/flush.h
  src/include/librpma.h
  src/mr.c
  src/mr.h
  src/peer.c
  src/peer.h
  src/peer_cfg.c
  tests/unit/common/mocks-rpma-conn.c
  tests/unit/common/mocks-rpma-flush.c
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/common/mocks-rpma-peer.c
  tests/unit/ep/ep-common.c
  tests/unit/peer/peer-create_qp.c
  tests/unit/peer/peer-mr_reg.c
Labels: sprint goal

#478 rpma: write 'DEBUGGING AND ERROR HANDLING' section of manual
  src/include/librpma.h
Labels: sprint goal

#485 common: threads awareness added to log
  src/include/librpma.h
  src/log.c
  src/log_internal.h
  tests/unit/common/mocks-rpma-log.c
Labels: sprint goal

#484 rpma: librpma.7: Direct Write to PMem
  src/include/librpma.h
Labels: sprint goal

#486 doc: add SEE ALSO section utils and peer
  src/include/librpma.h
Labels: sprint goal

#488 doc: add SEE ALSO section mr
  src/include/librpma.h
Labels: sprint goal

#489 doc: librpma.7: Client Operation
  src/include/librpma.h
Labels: sprint goal

#490 doc: add SEE ALSO section (conn)
  src/include/librpma.h
Labels: sprint goal

#495 doc: add SEE ALSO section (ep, rpma)
  src/include/librpma.h
Labels: sprint goal

#496 doc: add SEE ALSO section (completion, err, log)
  src/include/librpma.h
Labels: sprint goal

#504 doc: improve librpma.7 formatting
  src/include/librpma.h
Labels: sprint goal

#491 doc: librpma.7: Server Operation
  src/include/librpma.h
Labels: sprint goal

#497 rpma: write 'MEMORY MANAGEMENT' section of manual
  src/include/librpma.h
Labels: sprint goal

#501 doc: librpma.7: sync and async modes
  src/include/librpma.h
Labels: sprint goal
