Repository pmem/rpma, pull requests merged in 2021-12, with the labels that each got.

#1373 tools: reorder modes in SETTINGS_BY_MODE
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1377 tools: perf: prepare lib.benchmark and lib.figure... (fix)
  tools/perf/lib/compare.py
Labels: bug fix

#1375 tools: perf: document lib.Requirement
  tools/perf/lib/Requirement.py
  tools/perf/lib/bench.py
Labels: documentation, sprint goal

#1387 tools: add error raising in run_sync function
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1388 common: disable TEST_PYTHON_TOOLS in Debian 9 and CentOS 7
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  utils/docker/build.sh
  utils/docker/run-build.sh
Labels: sprint goal

#1379 tools: perf: lib.report reorg
  tools/perf/CMakeLists.txt
  tools/perf/lib/Part.py
  tools/perf/lib/Report.py
  tools/perf/lib/figure/base.py
  tools/perf/lib/kvtable.py
  tools/perf/lib/report/__init__.py
  tools/perf/lib/report/base.py
  tools/perf/lib/report/part.py
  tools/perf/lib/report/utils.py
  tools/perf/report_create.py
  tools/perf/tests/lib/report/kvtable/__init__.py
  tools/perf/tests/lib/report/kvtable/test_lines2str.py
  tools/perf/tests/lib/report/part/__init__.py
  tools/perf/tests/lib/report/part/test_init.py
  tools/perf/tests/lib/report/test_init.py
Labels: sprint goal

#1383 tools: perf: document lib.common
  tools/perf/CMakeLists.txt
  tools/perf/lib/common.py
Labels: documentation, sprint goal

#1378 tools: set names of log files
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1384 tools: perf: document lib.compare
  tools/perf/CMakeLists.txt
  tools/perf/lib/compare.py
Labels: documentation, sprint goal

#1386 tools: perf: document lib.remote_cmd
  tools/perf/lib/remote_cmd.py
Labels: documentation, sprint goal

#1381 tools: perf: document lib.report
  tools/perf/lib/report/__init__.py
  tools/perf/lib/report/base.py
  tools/perf/lib/report/part.py
  tools/perf/lib/report/utils.py
Labels: documentation, sprint goal

#1385 tools: perf: document lib.format
  tools/perf/CMakeLists.txt
  tools/perf/lib/format/__init__.py
  tools/perf/lib/format/fio.py
  tools/perf/lib/format/ib_read_bw.py
  tools/perf/lib/format/ib_read_lat.py
Labels: documentation, sprint goal

#1382 tools: perf: document lib.benchmark.runner
  tools/perf/lib/benchmark/base.py
  tools/perf/lib/benchmark/runner/__init__.py
  tools/perf/lib/benchmark/runner/base.py
  tools/perf/lib/benchmark/runner/bash.py
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/dummy.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: documentation, sprint goal

#1352 tools: ib_read.py: implement __server_start and __server_stop
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1389 test: fix the test_dict2kvtable.py test
  tests/tools/perf/kvtable/test_dict2kvtable.py
Labels: sprint goal, bug fix

#1390 tools: perf: document lib.report (fix)
  tools/perf/lib/report/base.py
  tools/perf/lib/report/part.py
Labels: documentation, sprint goal

#1392 tools: cpuload is an x-axis in case of the lat-cpu mode (fix)
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal, bug fix

#1394 tools: clean up base.py
  tools/perf/lib/benchmark/runner/base.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1396 tools: iterate the dictionary directly instead of calling .keys() (fix)
  tools/perf/lib/report/base.py
Labels: sprint goal, bug fix

#1395 tools: implement __result_append and __result_is_done
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1346 tools: ib_read.py: implement __client_run
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/lib/format/ib_read_bw.py
  tools/perf/lib/format/ib_read_lat.py
Labels: sprint goal

#1402 tools: fix setting paths of ib tools
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal, bug fix

#1401 tools: implement __set_DDIO
  tools/perf/lib/Requirement.py
Labels: sprint goal

#1399 tools: print message at the beginning of the benchmark
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1405 tools: fix reading AUX_PARAMS and REMOTE_AUX_PARAMS
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal, bug fix

#1404 tools: fix capturing stdout and stderr in subprocess.run()
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal, bug fix

#1406 tools: retry to connect the client of ib tool
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal, bug fix

#1407 tools: remove not allowed spaces (fix)
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/lib/format/ib_read_bw.py
  tools/perf/lib/format/ib_read_lat.py
Labels: sprint goal, bug fix

#1408 tools: fix reading AUX_PARAMS and REMOTE_AUX_PARAMS
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal, bug fix

#1409 tools: add warning message if variables are not set
  tools/perf/lib/Requirement.py
Labels: enhancement, sprint goal

#1410 test: enable the sysconf mock only in the main of unit tests
  tests/unit/common/mocks-unistd.c
  tests/unit/common/mocks-unistd.h
  tests/unit/flush/flush-apm_do.c
  tests/unit/flush/flush-new.c
Labels: bug fix, inter-sprint

#1309 common: add Ubuntu 21.10 to Nightly workflow
  .github/workflows/nightly.yml
  utils/docker/images/Dockerfile.ubuntu-21.10
Labels: enhancement, build system, inter-sprint

#1391 tools: fio.py SETTINGS_BY_MODE filled up
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1414 tools: fix result_is_done()
  tools/perf/lib/benchmark/runner/common.py
Labels: sprint goal, bug fix

#1415 tools: enable checking tuples in result_is_done() (fix)
  tools/perf/lib/benchmark/runner/common.py
Labels: sprint goal, bug fix

#1413 tools: add cpuload to X_KEYS (fix)
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal, bug fix

#1420 tools: check also a list in result_is_done() (fix)
  tools/perf/lib/benchmark/runner/common.py
Labels: sprint goal, bug fix

#1419 tools: fix collect_results() in base.py
  tools/perf/lib/figure/base.py
Labels: sprint goal, bug fix

#1412 tools: fio.py: implement __server_start and __server_stop
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1417 tools: fio.py: implement __client_run()
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1422 tools: fio.py: fix setting busy_wait_polling
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal, bug fix

#1424 tools: move all constants to the end of file
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1425 tools: do not use cpuio engine when cpuload==0 (fix)
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal, bug fix

#1430 tools: make sure all results are numbers
  tools/perf/lib/format/fio.py
  tools/perf/lib/format/ib_read_bw.py
Labels: sprint goal, bug fix

#1423 tools: stop the server when the client failed
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal, bug fix

#1435 tools: decode the error message in run_sync() (fix)
  tools/perf/lib/remote_cmd.py
Labels: sprint goal, bug fix

#1429 tools: make sure all values are ints before sorting them
  tools/perf/lib/figure/image.py
Labels: sprint goal

#1437 tools: codespell fixes
  tools/perf/BENCHMARKING.md
  tools/perf/lib/benchmark/base.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/common.py
  tools/perf/lib/format/fio.py
  tools/perf/lib/report/__init__.py
  tools/perf/report_create.py
  tools/perf/report_figures.py
Labels: sprint goal

#1428 tools: fix message in __server_start()
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1427 tools: add remote_command_pre/post
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1438 tools: fix dumping command of the fio server
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal, bug fix

#1442 tools: fix bad-whitespace errors
  tools/perf/lib/benchmark/runner/common.py
Labels: sprint goal, bug fix

#1441 tools: fix RemoteCmd
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1393 tools: adjust existing figures to the new python framework
  tools/perf/figures/cpuload.json
  tools/perf/figures/mix.json
  tools/perf/figures/read.json
  tools/perf/figures/write.json
Labels: sprint goal

#1443 common: add Debian 10 to On_Pull_Request CI builds
  .github/workflows/on_pull_request.yml
Labels: build system

#1444 common: add Debian 10 to On_Pull_Request CI builds
  .github/workflows/on_pull_request.yml
Labels: enhancement, build system

#1440 test: add simple test for the base runner
  tools/perf/tests/lib/benchmark/conftest.py
  tools/perf/tests/lib/benchmark/test_run.py
Labels: sprint goal

#1445 tools: change way of importing shutil.which()
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1446 tools: check required keys of oneseries
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1447 tools: unify error messages and exceptions
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1449 tools: improve setting dumping commands
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1450 tools: fio: verify if tool_mode has a correct value
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1433 tools: follow Abstract Factory design patter to call proper runner
  tools/perf/lib/benchmark/base.py
  tools/perf/lib/benchmark/runner/__init__.py
  tools/perf/lib/benchmark/runner/executor.py
  tools/perf/tests/lib/benchmark/test_run.py
Labels: inter-sprint

#1462 tools: run pylint on the tests of the runners
  tools/perf/CMakeLists.txt
  tools/perf/tests/lib/benchmark/runner/test_bash_run.py
  tools/perf/tests/lib/benchmark/runner/test_dummy_run.py
Labels: sprint goal

#1451 tools: fix collect_results() when collecting mix workloads
  tools/perf/lib/figure/base.py
Labels: sprint goal, bug fix

#1465 tools: pylint accepts long name
  utils/pylint.rc
Labels: build system, inter-sprint
