Repository pmem/rpma, pull requests merged in 2021-09, with the labels that each got.

#1240 tools: perf: close matplotlib.pyplot.figure's
  tools/perf/lib/figure.py
Labels: sprint goal

#1241 tools: perf: add footer with ref (fix)
  tools/perf/templates/part_footer.md
Labels: sprint goal

#1242 tools: perf: introduce page-breaks for more reasonable printing
  tools/perf/templates/layout.html
  tools/perf/templates/part_cpuload.md
  tools/perf/templates/part_mix.md
  tools/perf/templates/part_read.md
  tools/perf/templates/part_write.md
Labels: sprint goal

#1243 tools: perf: align data tables to the right
  tools/perf/lib/figure.py
  tools/perf/templates/layout.html
  tools/perf/tests/lib/figure/test_html_data_table.py
Labels: sprint goal

#1246 tools: perf: separate figure.series_in from figure.series
  tools/perf/lib/Benchmark.py
  tools/perf/lib/figure.py
  tools/perf/tests/lib/figure/test_html_data_table.py
Labels: sprint goal

#1247 tools: escape markdown special characters in configuration
  tools/perf/lib/Report.py
  tools/perf/lib/common.py
Labels: sprint goal

#1248 tools: remove the old Benchmarking toolchain
  tools/perf/.gitignore
  tools/perf/create_report.py
  tools/perf/create_report_figures.sh
  tools/perf/csv_compare.py
  tools/perf/report_bench.sh
  tools/perf/templates/appendices.md
  tools/perf/templates/appendices_header.md
  tools/perf/templates/appendices_menu.html
  tools/perf/templates/audience.md
  tools/perf/templates/authors.md.copyme
  tools/perf/templates/bios.md.copyme
  tools/perf/templates/configuration_common.md.copyme
  tools/perf/templates/configuration_target.md.copyme
  tools/perf/templates/disclaimer.md
  tools/perf/templates/introduction.md
  tools/perf/templates/part_preamble.md
  tools/perf/templates/part_read.md
  tools/perf/templates/report.md
  tools/perf/templates/report_menu.html
  tools/perf/templates/security.md.copyme
  tools/perf/templates/tc1_read.md
  tools/perf/templates/tc2_write.md
  tools/perf/templates/tc3_mix.md
  tools/perf/templates/tc4_cpu.md
  tools/perf/templates/tc_cpu_bw_config.md.copyme
  tools/perf/templates/tc_cpu_lat_config.md.copyme
  tools/perf/templates/tc_mix_bw_config.md.copyme
  tools/perf/templates/tc_mix_lat_config.md.copyme
  tools/perf/templates/tc_read_bw_config.md.copyme
  tools/perf/templates/tc_read_lat_config.md.copyme
  tools/perf/templates/tc_write_bw_config.md.copyme
  tools/perf/templates/tc_write_lat_config.md.copyme
Labels: sprint goal

#1244 tools: fix y-axis to 110% of max
  tools/perf/lib/figure.py
  tools/perf/report.json.example
  tools/perf/report_figures.py
Labels: sprint goal

#1205 common: add Rocky Linux and VzLinux to the nightly CI builds
  .github/workflows/nightly.yml
  utils/docker/images/Dockerfile.rockylinux-8.4
  utils/docker/images/Dockerfile.vzlinux-latest
Labels: enhancement

#1251 tools: do nothing if src and dst specify the same file
  tools/perf/report_create.py
Labels: sprint goal

#1252 tools: perf: append 'Testing date' to each config table
  tools/perf/lib/Report.py
  tools/perf/tests/lib/report/test_init.py
Labels: sprint goal

#1249 tools: perf: introduce common series params
  tools/perf/lib/figure.py
  tools/perf/tests/lib/figure/test_html_data_table.py
Labels: sprint goal

#1250 tools: perf: introduce a way to regenerate file.json files
  tools/perf/lib/figure.py
  tools/perf/report_figures.py
Labels: sprint goal

#1264 tools: perf: made all data tables take 100% of the width
  tools/perf/templates/layout.html
Labels: sprint goal

#1265 tools: add reference to the BENCHMARKING.md
  tools/perf/templates/part_preamble.md
Labels: sprint goal

#1266 tools: add reference to the BENCHMARKING.md
  tools/perf/templates/part_preamble.md
Labels: sprint goal

#1268 tools: document the 'continue' option of report_bench.py
  tools/perf/BENCHMARKING.md
Labels: sprint goal

#1273 tools: save intermediate files in case of an error
  tools/perf/ib_read.sh
  tools/perf/rpma_fio_bench.sh
Labels: sprint goal

#1276 tools: remove the name argument of pytest.fixture()
  tools/perf/tests/lib/benchmark/test_run.py
  utils/docker/images/Dockerfile.centos-7
Labels: bug fix

#1285 rpma: add rpma_mr_advise() to src/librpma.map file
  src/librpma.map
Labels: sprint goal, bug fix

#1284 common: add missing CMake file
  CMakeLists.txt
  cmake/FindLIBPMEM.cmake
Labels: bug fix

#1288 tools: do really skip the test
  tools/perf/bench_common.sh
Labels: sprint goal, bug fix

#1289 rpma: implement separate receive CQ (fix)
  src/include/librpma.h
Labels: bug fix

#1291 tools: perf: take requirements into account...
  tools/perf/lib/Benchmark.py
Labels: sprint goal
