Repository pmem/rpma, pull requests merged in 2021-02, with the labels that each got.

#804 tools: layout lat_pctls add missing xscale (fix)
  tools/csv_compare.py
Labels: sprint goal

#806 tools: add lat_pctls to the croppable layouts group
  tools/csv_compare.py
Labels: sprint goal

#802 rpma: add RDMA_CM_EVENT_REJECTED event handler
  examples/01-connection/client.c
  src/conn.c
  src/include/librpma.h
  src/rpma.c
  tests/unit/conn/conn-next_event.c
  tests/unit/utils/utils-conn_event_2str.c
Labels: sprint goal

#807 tools: adjust the report menu and link to the headers
  tools/templates/bios.md.template
  tools/templates/configuration_common.md.template
  tools/templates/configuration_target.md.template
  tools/templates/layout.html
  tools/templates/security.md.template
Labels: sprint goal

#805 tools: name files output_1 and output_2 after the split
  tools/csv_compare.py
Labels: sprint goal

#809 tools: remove waiting for server
  tools/rpma_fio_bench.sh
Labels: sprint goal

#815 tools: add a margin at the bottom of the chart (100px)
  tools/csv_compare.py
Labels: sprint goal

#816 tools: scale the chart title size according to width of the chart
  tools/csv_compare.py
Labels: sprint goal

#801 tools: update BENCHMARKING.md file
  tools/BENCHMARKING.md
Labels: sprint goal

#817 tools: do not append to global AUX_PARAMS
  tools/ib_read.sh
Labels: sprint goal

#803 tools: create_report_figures.sh big revamp
  tools/create_report_figures.sh
Labels: sprint goal

#821 tools: introduce LOG_CMDS
  tools/ib_read.sh
  tools/rpma_fio_bench.sh
Labels: sprint goal

#808 tools: add introduction to the report
  tools/create_report.py
  tools/templates/introduction.md.template
  tools/templates/layout.html
  tools/templates/report.md
Labels: sprint goal

#814 tools: add all report parts
  tools/create_report.py
  tools/templates/.gitignore
  tools/templates/layout.html
  tools/templates/report.md
  tools/templates/tc1_read.md
  tools/templates/tc2_write.md
  tools/templates/tc3_mix.md
  tools/templates/tc_config_dummy.md
Labels: sprint goal

#820 tools: set read lat & bw configs for ib_read_*
  tools/create_report.py
  tools/templates/.gitignore
  tools/templates/tc1_read.md
  tools/templates/tc_config.md.template
  tools/templates/tc_config_dummy.md
Labels: sprint goal

#825 tools: remove iomem_align from the FIO job files
  tools/fio_jobs/librpma-client-bw.fio
  tools/fio_jobs/librpma-client-lat.fio
  tools/fio_jobs/librpma_gpspm-server.fio
Labels: sprint goal

#826 tools: add proper write/mix config
  tools/create_report.py
  tools/templates/tc2_write.md
  tools/templates/tc3_mix.md
Labels: sprint goal

#827 tools: remove the introduction menu entry duplicate
  tools/templates/layout.html
Labels: sprint goal

#829 tools: rename OFED -> rdma-core and get rid of the irrelevant NIC
  tools/templates/configuration_common.md.template
Labels: sprint goal

#830 tools: introduction: fix the Figure 0 reference
  tools/templates/introduction.md.template
Labels: sprint goal

#834 tools: choose the chart title location conditionally
  tools/csv_compare.py
Labels: sprint goal

#828 tools: rename Figure_0 to Figure_000
  tools/create_report.py
  tools/templates/introduction.md.template
Labels: sprint goal

#832 tools: introduce two separate execution paths: report and appendices
  tools/create_report.py
Labels: sprint goal

#831 tools: add test case descriptions
  tools/templates/tc1_read.md
  tools/templates/tc2_write.md
  tools/templates/tc3_mix.md
Labels: sprint goal

#837 doc: describe paragraph running workloads
  documentation/perf-tuning-latency.md
Labels: sprint goal

#833 tools: take out the menu from the layout to a dedicated file
  tools/create_report.py
  tools/templates/layout.html
Labels: sprint goal

#823 tools: move DDIO's steps out of the loop
  tools/rpma_fio_bench.sh
Labels: sprint goal

#835 tools: intrudce appendices generation
  tools/create_report.py
  tools/templates/.gitignore
  tools/templates/appendices.md
  tools/templates/appendices_header.md
  tools/templates/appendices_menu.html
  tools/templates/layout.html
  tools/templates/report_header.md
Labels: sprint goal

#840 tools: improve BENCHMARKING.md
  tools/BENCHMARKING.md
Labels: sprint goal

#824 doc: HW & SW setup starting point description
  documentation/basic-hw_sw_setup_starting_point.md
  index.md
Labels: sprint goal

#844 doc: performance tuning - cleanup
  documentation/perf-tuning.md
  index.md
Labels: sprint goal

#843 tools: take out the menu from the layout to a dedicated file (fix)
  tools/templates/.gitignore
  tools/templates/report_menu.html
Labels: sprint goal

#842 doc: Direct Write to PMem - cleanup
  documentation/basic-direct-write-to-pmem.md
  index.md
Labels: sprint goal

#848 tools: remove the hamburger menu (does not look good on printouts)
  tools/templates/layout.html
Labels: sprint goal

#846 tools: unify the 'filename' option
  tools/rpma_fio_bench.sh
Labels: sprint goal

#854 tools: fix typos in tc1_read.md and tc2_write.md
  tools/templates/tc1_read.md
  tools/templates/tc2_write.md
Labels: sprint goal

#853 examples: link 10-send-with-imm example with librt for glibc<2.17
  examples/10-send-with-imm/CMakeLists.txt
Labels: sprint goal

#850 tools: reorganize / cleanup the templates directory
  tools/BENCHMARKING.md
  tools/create_report.py
  tools/templates/.gitignore
  tools/templates/audience.md
  tools/templates/authors.md.copyme
  tools/templates/bios.md.copyme
  tools/templates/configuration_common.md.copyme
  tools/templates/configuration_target.md.copyme
  tools/templates/introduction.md
  tools/templates/security.md.copyme
  tools/templates/tc_mix_bw_config.md.copyme
  tools/templates/tc_mix_lat_config.md.copyme
  tools/templates/tc_read_bw_config.md.copyme
  tools/templates/tc_read_lat_config.md.copyme
  tools/templates/tc_write_bw_config.md.copyme
  tools/templates/tc_write_lat_config.md.copyme
Labels: sprint goal

#863 doc: separate README and BENCHMARKING files
  tools/perf/BENCHMARKING.md
  tools/perf/README.md
Labels: bug fix, documentation

#864 doc: fix link to BENCHMARKING.md after moving it to perf
  documentation/perf-tuning.md
Labels: bug fix, documentation, sprint goal

#871 common: remove Ubuntu 16.04 and unneeded scripts for installing ndctl and pmdk
  .github/workflows/nightly.yml
  INSTALL.md
  utils/docker/build.sh
  utils/docker/images/Dockerfile.debian-9
  utils/docker/images/Dockerfile.ubuntu-16.04
  utils/docker/images/install-libndctl.sh
  utils/docker/images/install-pmdk.sh
  utils/docker/pull-or-rebuild-image.sh
Labels: sprint goal

#866 rpma: mmap() memory for rpma_mr_reg() in rpma_flush_apm_new()
  src/flush.c
  src/flush.h
  src/include/librpma.h
  tests/integration/common/mocks.c
  tests/integration/common/mocks.h
  tests/integration/example-01-connection/CMakeLists.txt
  tests/integration/example-01-connection/example-01-connection.c
  tests/integration/example-02-read-to-volatile/CMakeLists.txt
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
  tests/integration/example-04-write-to-persistent/CMakeLists.txt
  tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/common/mocks-stdlib.c
  tests/unit/common/mocks-stdlib.h
  tests/unit/conn/conn-new.c
  tests/unit/flush/CMakeLists.txt
  tests/unit/flush/flush-common.c
  tests/unit/flush/flush-common.h
  tests/unit/flush/flush-new.c
Labels: sprint goal

#872 tools: add dependencies to reporting tools
  tools/perf/BENCHMARKING.md
Labels: sprint goal

#869 rpma: send 0B massage
  examples/10-send-with-imm/client.c
  examples/10-send-with-imm/server.c
  examples/run-all-on-SoftRoCE.sh
  src/conn.c
  src/include/librpma.h
  src/mr.c
  src/mr.h
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/conn/conn-send.c
  tests/unit/conn/conn-send_with_imm.c
  tests/unit/mr/mr-send.c
Labels: sprint goal

#880 tools: add a disclaimer to the report
  tools/perf/create_report.py
  tools/perf/templates/disclaimer.md
  tools/perf/templates/report.md
Labels: sprint goal

#881 rpma: correct the order of src_addr and dst_addr
  src/mr.c
Labels: sprint goal

#903 examples: fix expected completion's op in the 04 example
  examples/04-write-to-persistent/client.c
Labels: bug fix

#906 common: fix typo in "unexpected"
  examples/08-messages-ping-pong/server.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/10-send-with-imm/server.c
  examples/11-write-with-imm/server.c
  examples/common/common-conn.c
  tests/unit/conn/conn-completion_get.c
Labels: bug fix

#908 test: increase MAX_ADDR in rpma_utils_get_ibv_context.c
  tests/multithreaded/utils/rpma_utils_get_ibv_context.c
Labels: bug fix

#904 rpma: handle success in rpma_err_2str()
  src/rpma_err.c
  tests/unit/error/error.c
Labels: enhancement
