Repository pmem/rpma, pull requests merged in 2021-11, with the labels that each got.

#1322 tools: perf: allow running benchmarks via various runners
  tools/perf/CMakeLists.txt
  tools/perf/lib/Benchmark.py
  tools/perf/lib/Requirement.py
  tools/perf/lib/bench.py
  tools/perf/lib/benchmark/__init__.py
  tools/perf/lib/benchmark/base.py
  tools/perf/lib/benchmark/runner/__init__.py
  tools/perf/lib/benchmark/runner/bash.py
  tools/perf/lib/benchmark/runner/dummy.py
  tools/perf/tests/lib/bench/test_new.py
  tools/perf/tests/lib/benchmark/conftest.py
  tools/perf/tests/lib/benchmark/runner/__init__.py
  tools/perf/tests/lib/benchmark/runner/test_bash_run.py
  tools/perf/tests/lib/benchmark/runner/test_dummy_run.py
  tools/perf/tests/lib/benchmark/test_run.py
  utils/pylint.rc
Labels: sprint goal

#1325 examples: fix memory leak in the 09 example
  examples/09-flush-to-persistent-GPSPM/server.c
Labels: bug fix

#1328 tools: perf: BaseRunner and IbReadRunner (scaffolding)
  tools/perf/lib/benchmark/base.py
  tools/perf/lib/benchmark/runner/__init__.py
  tools/perf/lib/benchmark/runner/base.py
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/tests/lib/benchmark/runner/common/__init__.py
  tools/perf/tests/lib/benchmark/runner/fio/__init__.py
  tools/perf/tests/lib/benchmark/runner/ib_read/__init__.py
Labels: sprint goal

#1330 tools: perf: FioRunner (scaffolding)
  tools/perf/lib/benchmark/runner/fio.py
  utils/pylint.rc
Labels: sprint goal

#1331 tools: perf: introduce controling DDIO from the Python-level
  tools/perf/lib/Requirement.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1332 tools: perf: introduce lib.format
  tools/perf/csv2standardized.py
  tools/perf/lib/format/__init__.py
  tools/perf/lib/format/fio.py
  tools/perf/lib/format/ib_read_bw.py
  tools/perf/lib/format/ib_read_lat.py
  tools/perf/tests/lib/format/__init__.py
  tools/perf/tests/lib/format/test_fio.py
  tools/perf/tests/lib/format/test_ib_read_bw.py
  tools/perf/tests/lib/format/test_ib_read_lat.py
Labels: sprint goal

#1334 tools: perf: DDIO from the Python-level (fix)
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1333 tools: perf: lib.format.FioFormat.parse()
  tools/perf/fio_json2csv.py
  tools/perf/lib/format/fio.py
  tools/perf/tests/lib/format/fio.json
Labels: sprint goal

#1336 tools: add missing cls argument (fix)
  tools/perf/lib/Requirement.py
Labels: sprint goal, bug fix

#1340 common: add paramiko to $PYTHON_DEPS
  utils/docker/images/Dockerfile.archlinux-latest
  utils/docker/images/Dockerfile.centos-7
  utils/docker/images/Dockerfile.centos-8
  utils/docker/images/Dockerfile.centos-stream
  utils/docker/images/Dockerfile.debian-10
  utils/docker/images/Dockerfile.debian-11
  utils/docker/images/Dockerfile.debian-9
  utils/docker/images/Dockerfile.debian-experimental
  utils/docker/images/Dockerfile.debian-stable
  utils/docker/images/Dockerfile.debian-testing
  utils/docker/images/Dockerfile.fedora-26
  utils/docker/images/Dockerfile.fedora-27
  utils/docker/images/Dockerfile.fedora-28
  utils/docker/images/Dockerfile.fedora-29
  utils/docker/images/Dockerfile.fedora-30
  utils/docker/images/Dockerfile.fedora-31
  utils/docker/images/Dockerfile.fedora-32
  utils/docker/images/Dockerfile.fedora-33
  utils/docker/images/Dockerfile.fedora-34
  utils/docker/images/Dockerfile.fedora-rawhide
  utils/docker/images/Dockerfile.opensuse-leap-latest
  utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
  utils/docker/images/Dockerfile.rockylinux-8.4
  utils/docker/images/Dockerfile.ubuntu-18.04
  utils/docker/images/Dockerfile.ubuntu-20.04
  utils/docker/images/Dockerfile.ubuntu-21.04
  utils/docker/images/Dockerfile.ubuntu-rolling
  utils/docker/images/Dockerfile.vzlinux-latest
Labels: sprint goal

#1341 tools: fix IB_PATH in ib_read.sh
  tools/perf/ib_read.sh
Labels: sprint goal, bug fix

#1343 tools: do not introduce a new temporary variable
  tools/perf/lib/Requirement.py
Labels: sprint goal

#1338 tools: check if fio is present locally
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1342 tools: verify if key is in the figure (fix)
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal, bug fix

#1339 tools: running commands on remote node over SSH
  tools/perf/BENCHMARKING.md
  tools/perf/CMakeLists.txt
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1344 tools: make old bash test framework the second option
  tools/perf/BENCHMARKING.md
Labels: sprint goal

#1348 common: add scp to $PYTHON_DEPS
  utils/docker/images/Dockerfile.archlinux-latest
  utils/docker/images/Dockerfile.centos-7
  utils/docker/images/Dockerfile.centos-8
  utils/docker/images/Dockerfile.centos-stream
  utils/docker/images/Dockerfile.debian-10
  utils/docker/images/Dockerfile.debian-11
  utils/docker/images/Dockerfile.debian-9
  utils/docker/images/Dockerfile.debian-experimental
  utils/docker/images/Dockerfile.debian-stable
  utils/docker/images/Dockerfile.debian-testing
  utils/docker/images/Dockerfile.fedora-26
  utils/docker/images/Dockerfile.fedora-27
  utils/docker/images/Dockerfile.fedora-28
  utils/docker/images/Dockerfile.fedora-29
  utils/docker/images/Dockerfile.fedora-30
  utils/docker/images/Dockerfile.fedora-31
  utils/docker/images/Dockerfile.fedora-32
  utils/docker/images/Dockerfile.fedora-33
  utils/docker/images/Dockerfile.fedora-34
  utils/docker/images/Dockerfile.fedora-rawhide
  utils/docker/images/Dockerfile.opensuse-leap-latest
  utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
  utils/docker/images/Dockerfile.rockylinux-8.4
  utils/docker/images/Dockerfile.ubuntu-18.04
  utils/docker/images/Dockerfile.ubuntu-20.04
  utils/docker/images/Dockerfile.ubuntu-21.04
  utils/docker/images/Dockerfile.ubuntu-rolling
  utils/docker/images/Dockerfile.vzlinux-latest
Labels: sprint goal

#1349 tools: perf: allow long triple-quoted strings
  tools/perf/lib/figure.py
  tools/perf/report_bench.py
  utils/pylint.rc
Labels: sprint goal

#1353 tools: fix name of the f argument in figure.py
  tools/perf/lib/figure.py
Labels: sprint goal, bug fix

#1345 tools: check if ib_tool is present remotely
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1350 tools: copy file to a remote node
  tools/perf/BENCHMARKING.md
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1354 tools: check if fio is present remotely
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1355 tools: replace the cmd argument with a list
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1356 tools: perf: update CONTRIBUTING.md
  tools/perf/.gitignore
  tools/perf/CONTRIBUTING.md
Labels: sprint goal

#1351 tools: ib_read.py: add __append_common_args
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1358 tools: perf: seal lib.bench
  tools/perf/lib/Requirement.py
  tools/perf/lib/bench.py
  tools/perf/tests/lib/bench/test_new.py
Labels: sprint goal

#1357 tools: perf: improve scripts documentation
  tools/perf/report_bench.py
  tools/perf/report_create.py
  tools/perf/report_figures.py
  utils/pylint.rc
Labels: sprint goal

#1362 tools: perf: fix the benchmarking dump
  tools/perf/lib/Requirement.py
Labels: sprint goal

#1363 tools: perf: complete and incomplete end
  tools/perf/report_bench.py
Labels: sprint goal

#1360 tools: ib_read.py, SETTINGS_BY_MODE filled up
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1361 tools: perf: document lib & lib.bench modules
  tools/perf/CMakeLists.txt
  tools/perf/lib/__init__.py
  tools/perf/lib/bench.py
  tools/perf/report_bench.py
  tools/perf/report_create.py
  tools/perf/report_figures.py
Labels: documentation, sprint goal

#1364 tools: perf: reorg Figure.py and flat.py
  tools/perf/CMakeLists.txt
  tools/perf/lib/bench.py
  tools/perf/lib/common.py
  tools/perf/lib/figure/__init__.py
  tools/perf/lib/figure/base.py
  tools/perf/lib/figure/flat.py
  tools/perf/lib/flat.py
  tools/perf/tests/lib/bench/test_new.py
  tools/perf/tests/lib/figure/test_html_data_table.py
  tools/perf/tests/lib/figure/test_oneseries_derivatives.py
  tools/perf/tests/lib/figure/test_str2key.py
Labels: sprint goal

#1366 tools: perf: document lib.figure.flat module
  tools/perf/lib/__init__.py
  tools/perf/lib/figure/__init__.py
  tools/perf/lib/figure/flat.py
Labels: documentation, sprint goal

#1367 tools: perf: split lib.figure.base.Figure
  tools/perf/CMakeLists.txt
  tools/perf/lib/compare.py
  tools/perf/lib/figure/__init__.py
  tools/perf/lib/figure/base.py
  tools/perf/lib/figure/html.py
  tools/perf/lib/figure/image.py
  tools/perf/tests/lib/figure/test_html_data_table.py
Labels: sprint goal

#1372 tools: verify that the cmd argument is a list
  tools/perf/lib/remote_cmd.py
Labels: sprint goal

#1368 tools: perf: separate Figure and Benchmark oneseries
  tools/perf/lib/benchmark/base.py
  tools/perf/lib/common.py
  tools/perf/lib/figure/base.py
  tools/perf/lib/figure/flat.py
Labels: sprint goal

#1371 tools: perf: document lib.figure.{base,html,image}
  tools/perf/lib/bench.py
  tools/perf/lib/figure/__init__.py
  tools/perf/lib/figure/base.py
  tools/perf/lib/figure/flat.py
  tools/perf/lib/figure/html.py
  tools/perf/lib/figure/image.py
  tools/perf/tests/lib/bench/test_new.py
  tools/perf/tests/lib/figure/test_html_data_table.py
  tools/perf/tests/lib/figure/test_png_path.py
  tools/perf/tests/lib/report/test_init.py
Labels: documentation, sprint goal
