Repository pmem/rpma, pull requests merged in 2022-06, with the labels that each got.

#1798 rpma: five more functions are not thread-safe
  THREAD_SAFETY.md
Labels: documentation, sprint goal

#1799 rpma: add thread safety analysis of the librpma library
  THREAD_SAFETY.md
  src/include/librpma.h
  src/peer_cfg.c
  src/rpma_err.c
Labels: documentation, sprint goal

#1789 doc: add performance reports for Ice Lake
  reports/index.md
Labels: documentation, sprint goal

#1802 rpma: change order of NOT thread-safe API calls
  THREAD_SAFETY.md
Labels: sprint goal

#1768 test: enable user error messages with actual values
  tests/multithreaded/common/mtt.h
Labels: inter-sprint

#1800 test: Upgrade Circle CI to Ubuntu 22.04
  .circleci/config.yml
  tests/drd.supp
  tests/helgrind.supp
  tests/memcheck-libibverbs.supp
Labels: inter-sprint

#1769 rpma: make rpma_conn_cfg_set_cq_size thread-safe
  CMakeLists.txt
  cmake/functions.cmake
  src/conn_cfg.c
  tests/drd.supp
  tests/helgrind.supp
  tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c
Labels: inter-sprint

#1806 common: openSUSE Tumbleweed has been fixed, remove workaround
  utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
Labels: build system, inter-sprint

#1792 test: move all rpma_conn_cfg MT tests to a separate folder
  tests/multithreaded/CMakeLists.txt
  tests/multithreaded/conn/CMakeLists.txt
  tests/multithreaded/conn_cfg/CMakeLists.txt
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_cq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_sq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_timeout.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_new.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_cq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_rq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_timeout.c
Labels: build system, inter-sprint

#1803 rpma: rename rpma.c to utils.c as it is a utils functions src file.
  src/CMakeLists.txt
  src/utils.c
  tests/integration/example-01-connection/CMakeLists.txt
  tests/integration/example-02-read-to-volatile/CMakeLists.txt
  tests/integration/example-04-write-to-persistent/CMakeLists.txt
  tests/unit/common/mocks-rpma-utils.c
  tests/unit/utils/CMakeLists.txt
Labels: inter-sprint

#1807 test: revert running 32 threads in MT tests
  tests/multithreaded/run_group.cmake
Labels: sprint goal

#1810 test: add one suppression for rpma_conn_req_delete()
  tests/helgrind.supp
Labels: sprint goal

#1767 test: adapt rpma_perr_cfg_new mtt to the new test template
  tests/multithreaded/peer/rpma_peer_cfg_new.c
Labels: enhancement, inter-sprint

#1815 common: rename run-all-on-SoftRoCE.sh to run-all-examples.sh
  CMakeLists.txt
  examples/README.md
  examples/run-all-examples.sh
Labels: sprint goal

#1814 common: standardize RDMA configuration variable names
  .circleci/config.yml
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/multithreaded/run_group.cmake
  tools/config_softroce.sh
  utils/docker/run-build.sh
Labels: sprint goal

#1808 rpma: scaffolding of the DEVELOPMENT.md file
  DEVELOPMENT.md
  INSTALL.md
Labels: sprint goal

#1816 examples: run all examples with fault injection
  CMakeLists.txt
  examples/run-all-examples.sh
Labels: sprint goal

#1819 common: always set WORKDIR as a safe directory
  utils/docker/prepare-for-build.sh
Labels: build system

#1821 examples: do not wait additional 1 sec for running server
  examples/run-all-examples.sh
Labels: sprint goal

#1820 examples: add support for PMem to run-all-examples.sh
  examples/run-all-examples.sh
Labels: sprint goal

#1826 common: import missing GPG keys of CircleCI Ubuntu
  .circleci/install-pkgs-ubuntu.sh
Labels: build system, sprint goal

#1823 examples: always set S_FI_VAL and C_FI_VAL
  examples/run-all-examples.sh
Labels: sprint goal, bug fix

#1822 examples: run integration tests on SoftRoCE or RDMA HW
  DEVELOPMENT.md
  examples/run-all-examples.sh
Labels: sprint goal

#1818 common: documentation of running unit and multithreaded tests
  .circleci/config.yml
  CMakeLists.txt
  DEVELOPMENT.md
  utils/docker/run-build.sh
Labels: sprint goal

#1829 common: add python3 to openSUSE Leap Docker image (fix)
  utils/docker/images/Dockerfile.opensuse-leap-latest
Labels: build system, bug fix

#1825 common: documentation of building, installing and testing
  CONTRIBUTING.md
  DEVELOPMENT.md
  INSTALL.md
  README.md
Labels: sprint goal

#1830 test: increase timeout for pthread_cond_timedwait() to 60 seconds
  tests/multithreaded/common/mtt.c
Labels: sprint goal

#1835 test: add missing suppressions for drd and helgrind
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1832 test: update description to newly added suppressions
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1837 test: add new suppressions for drd and helgrind
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1838 common: turn on building examples in CI
  .circleci/config.yml
  utils/docker/run-build.sh
Labels: sprint goal, bug fix

#1839 common: fix CMake variables in run-build.sh
  utils/docker/run-build.sh
Labels: sprint goal, bug fix

#1840 rpma: fix a link in the README.md file
  README.md
Labels: sprint goal

#1834 test: remove old integration tests
  CHANGELOG.md
  tests/CMakeLists.txt
  tests/integration/CMakeLists.txt
  tests/integration/common/mocks.c
  tests/integration/common/mocks.h
  tests/integration/example-01-connection/CMakeLists.txt
  tests/integration/example-01-connection/example-01-connection.c
  tests/integration/example-02-read-to-volatile/CMakeLists.txt
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
  tests/integration/example-04-write-to-persistent/CMakeLists.txt
  tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c
  tests/unit/common/mocks-rdma_cm.c
  tests/unit/conn_req/conn_req-common.h
  tests/unit/conn_req/conn_req-connect.c
Labels: sprint goal

#1841 rpma: fix description of usage of PMem in the integration tests
  DEVELOPMENT.md
  examples/run-all-examples.sh
Labels: documentation, sprint goal, bug fix

#1843 rpma: turn on building examples by default
  .circleci/config.yml
  CHANGELOG.md
  CMakeLists.txt
  DEVELOPMENT.md
  utils/docker/run-build.sh
Labels: sprint goal

#1845 doc: remove non-existing option TEST_LONG
  DEVELOPMENT.md
Labels: documentation, sprint goal

#1844 rpma: remove the BUILD_CHECK_CSTYLE CMake variable
  CHANGELOG.md
  CMakeLists.txt
  DEVELOPMENT.md
  utils/docker/build.sh
  utils/docker/run-build.sh
Labels: build system, sprint goal

#1846 common: fix CMake variables in run-build.sh
  utils/docker/run-build.sh
Labels: sprint goal, bug fix

#1848 examples: fix checking IP address
  examples/run-all-examples.sh
Labels: sprint goal, bug fix

#1851 examples: fix checking a CLI argument
  examples/run-all-examples.sh
Labels: sprint goal, bug fix

#1850 test: suppression format definition
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1855 test: update suppressions of syslog
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1852 rpma: initialize flush_type to prevent a fault-injection error
  src/conn.c
Labels: sprint goal, bug fix

#1856 examples: fix verifying a path of PMem given in RPMA_EXAMPLES_PMEM_PATH
  examples/run-all-examples.sh
Labels: sprint goal, bug fix

#1857 rpma: rename get_timestamp_prefix to rpma_get_timestamp_prefix
  src/log_default.c
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1860 test: update suppression of ucma_init()
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1858 test: update suppressions of rpma_get_timestamp_prefix
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1863 test: fix expected value of cq_size
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_cq_size.c
Labels: sprint goal, bug fix

#1859 rpma: replace localtime() with localtime_r()
  src/log_default.c
  tests/drd.supp
  tests/helgrind.supp
  tests/unit/common/mocks-time.c
  tests/unit/log_default/CMakeLists.txt
  tests/unit/log_default/function.c
Labels: enhancement, sprint goal

#1866 test: fix checking if valgrind -s option is supported
  CMakeLists.txt
  cmake/functions.cmake
  tests/cmake/ctest_helpers.cmake
Labels: sprint goal, bug fix

#1870 test: RPMA_TESTING_IP cannot be set to 127.0.0.1
  tests/CMakeLists.txt
  tests/multithreaded/run_group.cmake
Labels: enhancement, sprint goal

#1868 test: add a notice when TESTS_USE_VALGRIND is OFF
  tests/cmake/ctest_helpers.cmake
Labels: enhancement, sprint goal

#1864 test: remove unused file
  tests/cmake/helpers.cmake
  tests/ld.supp
Labels: sprint goal

#1871 rpma: improve DEVELOPMENT.md file
  DEVELOPMENT.md
Labels: sprint goal

#1874 rpma: clean up and improve DEVELOPMENT.md file
  DEVELOPMENT.md
Labels: documentation, enhancement, sprint goal

#1880 common: remove the TESTS_USE_VALGRIND option
  .circleci/config.yml
  CHANGELOG.md
  CMakeLists.txt
  DEVELOPMENT.md
  tests/cmake/ctest_helpers.cmake
Labels: sprint goal

#1861 rpma: rpma_conn_cfg_set_... test modification and add suppresions
  tests/drd.supp
  tests/helgrind.supp
  tests/multithreaded/conn_cfg/CMakeLists.txt
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_rq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_timeout.c
Labels: sprint goal

#1881 common: replace the --fault-injection option with --integration-tests
  CMakeLists.txt
  DEVELOPMENT.md
  examples/run-all-examples.sh
Labels: sprint goal

#1876 common: MTT and integration tests require valgrind and RDMA connection
  CMakeLists.txt
  DEVELOPMENT.md
  examples/run-all-examples.sh
  tests/CMakeLists.txt
Labels: sprint goal

#1872 test: add rpma_ep_shutdown mt test
  tests/multithreaded/ep/CMakeLists.txt
  tests/multithreaded/ep/rpma_ep_shutdown.c
Labels: sprint goal

#1873 test: add rpma_mr_dereg mt test
  tests/multithreaded/mr/CMakeLists.txt
  tests/multithreaded/mr/rpma_mr_dereg.c
Labels: sprint goal

#1883 tools: configure SoftRoCE before build commands on CircleCi
  .circleci/config.yml
Labels: inter-sprint

#1862 test: update suppressions of libibverbs and librdmacm
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1893 doc: fix info about IP of RDMA-capable network interface
  DEVELOPMENT.md
Labels: documentation, sprint goal

#1895 examples: fix setting IP address of an RDMA-capable network interface
  examples/run-all-examples.sh
Labels: sprint goal, bug fix

#1896 test: fix names of two suppressions
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1877 rpma: coherent message about pmem library used by examples
  CMakeLists.txt
Labels: inter-sprint

#1888 rpma: set default value of CMAKE_BUILD_TYPE to Release
  CMakeLists.txt
Labels: inter-sprint
