Repository pmem/rpma, pull requests merged in 2022-04, with the labels that each got.

#1635 test: extract common code for MT tests
  tests/multithreaded/common/mtt_connect.c
  tests/multithreaded/common/mtt_connect.h
  tests/multithreaded/conn/CMakeLists.txt
  tests/multithreaded/conn/rpma_conn_get_private_data.c
  tests/multithreaded/conn/server_rpma_conn_get_private_data.c
Labels: sprint goal

#1639 rpma: add error message for RPMA_E_AGAIN
  CHANGELOG.md
  src/rpma_err.c
  tests/unit/error/error.c
Labels: sprint goal

#1640 doc: fix spelling errors
  documentation/basic-direct-write-to-pmem.md
  documentation/perf-tuning.md
  manpages/v0.9.0/rpma_mr_get_descriptor_size.3.md
Labels: sprint goal

#1636 tools: add checking xADR parameter for Ice Lake platforms
  tools/perf/CONFIG.JSON.md
  tools/perf/config.json.example
  tools/perf/lib/Requirement.py
Labels: sprint goal

#1638 doc: update pmem.io benchmarking manuals for ICX
  documentation/basic-direct-write-to-pmem.md
Labels: sprint goal

#1644 test: MTT: check if the child process terminated
  tests/multithreaded/common/mtt.c
Labels: sprint goal

#1646 rpma: add missing rpma_private_data_discard (fix)
  src/conn.c
  tests/unit/conn/conn-new.c
Labels: sprint goal, bug fix

#1645 examples: print out log file in case of error
  examples/run-all-on-SoftRoCE.sh
Labels: sprint goal

#1630 test: add the rpma_mr_remote_from_descriptor multithreaded test
  tests/multithreaded/common/mtt_connect.h
  tests/multithreaded/mr/CMakeLists.txt
  tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
  tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c
Labels: sprint goal

#1651 rpma: fix rpma_conn_get_compl_fd()
  CHANGELOG.md
  src/conn.c
  src/include/librpma.h
  src/rpma_err.c
  tests/unit/error/error.c
Labels: sprint goal, bug fix

#1649 rpma: add doc + ut for set/get_compl_channel
  doc/manuals_3.txt
  src/include/librpma.h
  tests/unit/conn_cfg/CMakeLists.txt
  tests/unit/conn_cfg/conn_cfg-compl_channel.c
Labels: sprint goal

#1654 rpma: add bool *is_rcq argument to rpma_conn_wait
  src/conn.c
  src/include/librpma.h
Labels: sprint goal

#1659 test: add mock of rpma_conn_cfg_get_compl_channel()
  tests/unit/common/mocks-rpma-conn_cfg.c
  tests/unit/common/mocks-rpma-conn_cfg.h
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-from_cm_event.c
  tests/unit/conn_req/conn_req-new.c
Labels: sprint goal

#1663 rpma: enable shared completion channel when there is no RCQ
  src/conn_req.c
Labels: sprint goal

#1655 rpma: add doc + ut for rpma_conn_wait()
  doc/manuals_3.txt
  src/conn.c
  src/include/librpma.h
  tests/unit/common/mocks-ibverbs.c
  tests/unit/common/mocks-ibverbs.h
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-common.c
  tests/unit/conn/conn-common.h
  tests/unit/conn/conn-wait.c
  tests/unit/cq/cq-common.c
  tests/unit/cq/cq-new_delete.c
  tests/unit/cq/cq-wait.c
Labels: sprint goal

#1668 rpma: remove rpma_ibv_create/destroy_comp_channel
  src/conn.c
  src/conn_req.c
  src/rpma.c
  src/rpma.h
  tests/unit/common/mocks-rpma-cq.c
  tests/unit/conn/conn-common.c
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-connect.c
  tests/unit/conn_req/conn_req-delete.c
  tests/unit/conn_req/conn_req-from_cm_event.c
  tests/unit/conn_req/conn_req-new.c
  tests/unit/conn_req/conn_req-private_data.c
Labels: sprint goal

#1650 test: add unit test and doc for rpma_conn_get_compl_fd()
  doc/manuals_3.txt
  src/include/librpma.h
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-get_compl_fd.c
Labels: sprint goal

#1669 test: rename predefined structures
  tests/unit/conn/conn-common.c
  tests/unit/conn/conn-common.h
  tests/unit/conn/conn-get_compl_fd.c
  tests/unit/conn/conn-new.c
  tests/unit/conn/conn-wait.c
Labels: sprint goal

#1666 test: verify channel in rpma_conn_new()
  tests/unit/common/mocks-rpma-conn.c
  tests/unit/conn_req/conn_req-common.h
  tests/unit/conn_req/conn_req-connect.c
Labels: sprint goal

#1672 test: rename Conn_with_rcq_and_channel to Conn_with_rcq_with_channel
  tests/unit/conn/conn-common.c
  tests/unit/conn/conn-common.h
  tests/unit/conn/conn-get_compl_fd.c
  tests/unit/conn/conn-wait.c
Labels: sprint goal

#1670 test: update CONN_TEST_SETUP_TEARDOWN_WITH_AND_WITHOUT_RCQ()
  tests/unit/conn/conn-common.h
  tests/unit/conn/conn-get_cq_rcq.c
  tests/unit/conn/conn-new.c
Labels: sprint goal

#1671 test: add Conn_no_rcq_with_channel
  tests/unit/conn/conn-common.c
  tests/unit/conn/conn-common.h
Labels: sprint goal

#1662 test: add missing unit tests for rpma_conn_delete()
  tests/unit/conn/conn-new.c
Labels: sprint goal

#1673 test: add missing test for rpma_conn_req_from_cm_event()
  tests/unit/conn_req/conn_req-from_cm_event.c
Labels: sprint goal

#1675 test: add missing tests for rpma_conn_req_delete()
  tests/unit/conn_req/conn_req-delete.c
Labels: sprint goal

#1679 common: set maximum line length to 100
  CONTRIBUTING.md
  utils/cstyle
Labels: sprint goal

#1680 common: set maximum line length to 100
  CONTRIBUTING.md
  utils/cstyle
Labels: sprint goal

#1678 rpma: update librpma.h and CHANGELOG
  CHANGELOG.md
  src/include/librpma.h
Labels: sprint goal

#1683 rpma: fix SYNOPSIS of rpma_conn_wait()
  src/include/librpma.h
Labels: sprint goal

#1686 rpma: fix memory leak in rpma_peer_delete()
  CHANGELOG.md
  src/peer.c
  tests/unit/peer/peer-common.c
  tests/unit/peer/peer-new.c
Labels: bug fix

#1690 examples: fix EXAMPLE_USE_LIBPMEM_IF_FOUND variable in CMakeLists.txt
  examples/CMakeLists.txt
Labels: sprint goal, bug fix

#1687 rpma: make timeout_ms always initialized (fix)
  src/conn_req.c
Labels: bug fix

#1688 rpma: make shared always initialized (fix)
  src/conn_req.c
Labels: sprint goal, bug fix

#1692 test: fix the delete__dealloc_pd_ERRNO unit test
  tests/unit/peer/peer-common.c
  tests/unit/peer/peer-new.c
Labels: sprint goal, bug fix

#1696 examples: add scaffolding of examples with SHared Completion CHannel
  examples/13-flush-to-persistent-GPSPM-SHCCH/CMakeLists.txt
  examples/13-flush-to-persistent-GPSPM-SHCCH/GPSPM_flush.pb-c.c
  examples/13-flush-to-persistent-GPSPM-SHCCH/GPSPM_flush.pb-c.h
  examples/13-flush-to-persistent-GPSPM-SHCCH/GPSPM_flush.proto
  examples/13-flush-to-persistent-GPSPM-SHCCH/README.md
  examples/13-flush-to-persistent-GPSPM-SHCCH/client.c
  examples/13-flush-to-persistent-GPSPM-SHCCH/flush-to-persistent-GPSPM.h
  examples/13-flush-to-persistent-GPSPM-SHCCH/server.c
  examples/14-receive-completion-queue-SHCCH/CMakeLists.txt
  examples/14-receive-completion-queue-SHCCH/README.md
  examples/14-receive-completion-queue-SHCCH/client.c
  examples/14-receive-completion-queue-SHCCH/receive-completion-queue-common.c
  examples/14-receive-completion-queue-SHCCH/receive-completion-queue-common.h
  examples/14-receive-completion-queue-SHCCH/server.c
  examples/15-multiple-connections-SHCCH/CMakeLists.txt
  examples/15-multiple-connections-SHCCH/README.md
  examples/15-multiple-connections-SHCCH/client.c
  examples/15-multiple-connections-SHCCH/multiple-connections-common.h
  examples/15-multiple-connections-SHCCH/server.c
  examples/CMakeLists.txt
  examples/run-all-on-SoftRoCE.sh
  utils/docker/run-build.sh
Labels: sprint goal

#1701 rpma: include log_default.h in log_internal.h (fix)
  src/log_internal.h
Labels: sprint goal, bug fix

#1705 examples: add common-conn.c and USE_LIBIBVERBS inside add_example()
  examples/CMakeLists.txt
Labels: sprint goal

#1704 examples: use shared completion channel in example 13 (server part)
  examples/13-flush-to-persistent-GPSPM-SHCCH/server.c
  examples/common/common-conn.c
  examples/common/common-conn.h
Labels: sprint goal

#1707 test: fix error handling path of rpma_mr_remote_from_descriptor MT test
  tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
  tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c
Labels: sprint goal, bug fix

#1706 examples: use shared completion channel in example 13 (client part)
  examples/13-flush-to-persistent-GPSPM-SHCCH/client.c
Labels: sprint goal

#1708 examples: use shared completion channel in example 14
  examples/14-receive-completion-queue-SHCCH/CMakeLists.txt
  examples/14-receive-completion-queue-SHCCH/client.c
  examples/14-receive-completion-queue-SHCCH/receive-completion-queue-common.c
  examples/14-receive-completion-queue-SHCCH/receive-completion-queue-common.h
  examples/14-receive-completion-queue-SHCCH/server.c
  examples/CMakeLists.txt
Labels: sprint goal

#1709 examples: improve README files (13, 14)
  examples/13-flush-to-persistent-GPSPM-SHCCH/README.md
  examples/14-receive-completion-queue-SHCCH/README.md
Labels: sprint goal

#1710 test: move rpma_peer_new() out of mtt_client_connect()
  tests/multithreaded/common/mtt_connect.c
  tests/multithreaded/common/mtt_connect.h
  tests/multithreaded/conn/rpma_conn_get_private_data.c
  tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
Labels: sprint goal

#1713 test: add common epoll functions to MT framework
  tests/multithreaded/common/mtt_common-epoll.c
  tests/multithreaded/common/mtt_common-epoll.h
Labels: sprint goal
