Repository pmem/rpma, pull requests merged in 2022-01, with the labels that each got.

#1470 tools: fix Executor.run()
  tools/perf/lib/benchmark/runner/executor.py
Labels: sprint goal

#1468 tools: disable bad-continuation pylint warning
  utils/pylint.rc
Labels: build system, sprint goal, bug fix

#1466 test: fix test_dict2kvtable.py
  tests/tools/perf/kvtable/test_dict2kvtable.py
Labels: sprint goal, bug fix

#1464 common: clean up lib.report.utils tests
  tests/tools/perf/kvtable/.gitignore
  tools/perf/tests/lib/report/utils/__init__.py
  tools/perf/tests/lib/report/utils/test_dict2kvtable.py
  tools/perf/tests/lib/report/utils/test_lines2str.py
Labels: sprint goal

#1463 common: clean up ignoring __pycache__
  tools/perf/.gitignore
  tools/perf/lib/.gitignore
Labels: sprint goal

#1467 tools: tool added to mandatory keys
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal, bug fix

#1473 common: do not run pytest if TEST_PYTHON_TOOLS is not ON (fix)
  utils/docker/run-build.sh
Labels: build system, sprint goal, bug fix

#1472 tools: verify if REMOTE_DIRECT_WRITE_TO_PMEM is in config
  tools/perf/lib/Requirement.py
Labels: sprint goal

#1452 tools: unit tests for runners initialization
  tools/perf/tests/lib/benchmark/conftest.py
  tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py
  tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py
Labels: sprint goal

#1475 common: Debian testing and experimental use pylint instead of pylint3
  utils/docker/images/Dockerfile.debian-experimental
  utils/docker/images/Dockerfile.debian-testing
Labels: build system, bug fix, inter-sprint

#1474 tools: check tools/perf/tests/lib/benchmark/*.py with pylint
  tools/perf/CMakeLists.txt
  tools/perf/tests/lib/benchmark/test_run.py
Labels: sprint goal

#1455 tools: ib_read_[lat|bw] defined in figure
  tools/perf/figures/read.json
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: sprint goal

#1471 tools: remove duplicate lines
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1477 tools: improve validating oneseries
  tools/perf/lib/benchmark/runner/common.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py
Labels: sprint goal

#1481 tools: add randread, randwrite and randrw to fio rw modes
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal, bug fix

#1480 tools: set timeout
  tools/perf/CONFIG.JSON.md
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1478 tools: fix continue mode
  tools/perf/lib/Requirement.py
  tools/perf/lib/benchmark/base.py
Labels: sprint goal

#1479 tools: add REMOTE_TRACER
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1476 tools: remove bash framework scripts
  tools/perf/BENCHMARKING.md
  tools/perf/bench_common.sh
  tools/perf/config.json.example
  tools/perf/csv2standardized.py
  tools/perf/csv_compare.py
  tools/perf/fio_json2csv.py
  tools/perf/ib_read.sh
  tools/perf/lib/Requirement.py
  tools/perf/lib/benchmark/base.py
  tools/perf/lib/benchmark/runner/__init__.py
  tools/perf/lib/benchmark/runner/bash.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/format/fio.py
  tools/perf/lib/format/ib_read_bw.py
  tools/perf/lib/format/ib_read_lat.py
  tools/perf/rpma_fio_bench.sh
  tools/perf/tests/lib/benchmark/conftest.py
  tools/perf/tests/lib/benchmark/test_run.py
Labels: sprint goal

#1485 tools: check if all required parameters are set in the config
  tools/perf/lib/bench.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
  tools/perf/tests/lib/bench/test_new.py
Labels: sprint goal, bug fix

#1487 tools: rename the '--names' option to '--prefixes'
  tools/perf/BENCHMARKING.md
  tools/perf/report_figures.py
Labels: sprint goal

#1484 tools: update BENCHMARKING.md and add simple example of figure
  tools/perf/BENCHMARKING.md
  tools/perf/figures/example_read.json
Labels: documentation, sprint goal

#1486 tools: document config.json parameters
  tools/perf/CONFIG.JSON.md
Labels: sprint goal

#1492 tools: replace REMOTE_JOB_MEM_PATH with REMOTE_PMEM_PATH
  tools/perf/CONFIG.JSON.md
  tools/perf/config.json.example
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1483 common: move CentOS_Stream CI build to Nightly_Experimental
  .github/workflows/nightly_experimental.yml
  .github/workflows/nightly_rebuild.yml
Labels: build system

#1501 tools: remove double check of ['filetype'] == 'malloc' condition
  tools/perf/lib/benchmark/runner/fio.py
Labels: sprint goal

#1500 tools: describe REMOTE_PMEM_PATH in details
  tools/perf/CONFIG.JSON.md
Labels: sprint goal, bug fix

#1507 tools: clarify the ddio.sh script usage
  tools/README.md
Labels: documentation, sprint goal

#1508 common: move OpenSUSE Tumbleweed back to Nightly
  .github/workflows/nightly.yml
  .github/workflows/nightly_experimental.yml
Labels: build system

#1505 examples: add rpma_mr_advise
  examples/05-flush-to-persistent/server.c
Labels: sprint goal

#1511 common: remove OSes that do not support IBV_ADVISE_MR_FLAG_FLUSH
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
Labels: build system, sprint goal

#1506 rpma: update CHANGELOG
  CHANGELOG.md
Labels: documentation, sprint goal

#1510 examples: add rpma_mr_advise to the rest of examples
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/server.c
  examples/07-atomic-write/server.c
  examples/09-flush-to-persistent-GPSPM/server.c
Labels: sprint goal

#1509 examples: explain <pmem-path> in PMEM_USAGE
  examples/03-read-to-persistent/README.md
  examples/03-read-to-persistent/client.c
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/README.md
  examples/04-write-to-persistent/client.c
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/README.md
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/07-atomic-write/README.md
  examples/07-atomic-write/server.c
  examples/09-flush-to-persistent-GPSPM/README.md
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/common/common-conn.h
Labels: sprint goal

#1512 common: 0.10.0-rc1 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#1514 rpma: update linker version script
  src/librpma.map
Labels: sprint goal

#1504 rpma: comparison of old and new API
  src/include/librpma.h
Labels: sprint goal

#1513 common: 0.10.0 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#979 rpma: implement rpma_cq_get_wc(3)
  doc/manuals_3.txt
  examples/02-read-to-volatile/client.c
  src/cq.c
  src/include/librpma.h
  src/librpma.map
  tests/unit/cq/CMakeLists.txt
  tests/unit/cq/cq-get_wc.c
Labels: sprint goal

#1516 common: rename gh-pages branch to man-pages
  utils/docker/run-doc-update.sh
Labels: sprint goal

#1503 tools: create html compare files
  tools/perf/lib/compare.py
  tools/perf/lib/figure/__init__.py
  tools/perf/lib/figure/html.py
  tools/perf/lib/figure/image.py
  tools/perf/report_figures.py
  tools/perf/templates/layout_cmp.html
Labels: sprint goal

#1502 common: add coverage library to docker images
  utils/docker/images/Dockerfile.archlinux-latest
  utils/docker/images/Dockerfile.centos-7
  utils/docker/images/Dockerfile.centos-8
  utils/docker/images/Dockerfile.centos-stream
  utils/docker/images/Dockerfile.debian-10
  utils/docker/images/Dockerfile.debian-11
  utils/docker/images/Dockerfile.debian-9
  utils/docker/images/Dockerfile.debian-experimental
  utils/docker/images/Dockerfile.debian-stable
  utils/docker/images/Dockerfile.debian-testing
  utils/docker/images/Dockerfile.fedora-26
  utils/docker/images/Dockerfile.fedora-27
  utils/docker/images/Dockerfile.fedora-28
  utils/docker/images/Dockerfile.fedora-29
  utils/docker/images/Dockerfile.fedora-30
  utils/docker/images/Dockerfile.fedora-31
  utils/docker/images/Dockerfile.fedora-32
  utils/docker/images/Dockerfile.fedora-33
  utils/docker/images/Dockerfile.fedora-34
  utils/docker/images/Dockerfile.fedora-rawhide
  utils/docker/images/Dockerfile.opensuse-leap-latest
  utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
  utils/docker/images/Dockerfile.rockylinux-8.4
  utils/docker/images/Dockerfile.ubuntu-18.04
  utils/docker/images/Dockerfile.ubuntu-20.04
  utils/docker/images/Dockerfile.ubuntu-21.04
  utils/docker/images/Dockerfile.ubuntu-21.10
  utils/docker/images/Dockerfile.ubuntu-rolling
  utils/docker/images/Dockerfile.vzlinux-latest
Labels: sprint goal

#1518 tools: add DEBUG_SKIP_REMOTE_CMDS config.json variable
  tools/perf/CONFIG.JSON.md
  tools/perf/lib/Requirement.py
  tools/perf/lib/bench.py
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: inter-sprint

#1520 tools: add _DEBUG prefix to the rest of debug config.json variables
  tools/perf/CONFIG.JSON.md
  tools/perf/lib/benchmark/runner/fio.py
  tools/perf/lib/benchmark/runner/ib_read.py
Labels: inter-sprint

#1519 examples: use rpma_cq_get_wc() in all examples
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/client.c
  examples/05-flush-to-persistent/client.c
  examples/06-multiple-connections/README.md
  examples/06-multiple-connections/server.c
  examples/07-atomic-write/client.c
  examples/08-messages-ping-pong/client.c
  examples/08-messages-ping-pong/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/10-send-with-imm/client.c
  examples/10-send-with-imm/server.c
  examples/11-write-with-imm/client.c
  examples/11-write-with-imm/server.c
Labels: sprint goal

#1524 common: update CHANGELOG.md
  CHANGELOG.md
Labels: sprint goal

#1523 common: remove unused Dockerfiles and update INSTALL.md
  INSTALL.md
  utils/docker/images/Dockerfile.debian-9
  utils/docker/images/Dockerfile.fedora-26
  utils/docker/images/Dockerfile.fedora-27
  utils/docker/images/Dockerfile.fedora-28
  utils/docker/images/Dockerfile.fedora-29
  utils/docker/images/Dockerfile.fedora-30
  utils/docker/images/Dockerfile.fedora-31
  utils/docker/images/Dockerfile.ubuntu-18.04
Labels: sprint goal

#1522 tools: update BENCHMARKING.md and config.json.example
  tools/perf/BENCHMARKING.md
  tools/perf/config.json.example
Labels: sprint goal

#1498 common: run-build.sh python test coverage
  utils/docker/run-build.sh
Labels: sprint goal
