Repository pmem/rpma, pull requests merged in 2022-02, with the labels that each got.

#1525 rpma: mark as deprecated rpma_cq_get_completion(), struct rpma_completion and enum rpma_op
  CHANGELOG.md
  src/include/librpma.h
Labels: sprint goal

#1530 examples: do not ignore correct arguments
  examples/05-flush-to-persistent/server.c
  examples/07-atomic-write/server.c
  examples/08-messages-ping-pong/client.c
  examples/10-send-with-imm/client.c
Labels: sprint goal

#1529 common: remove deprecated API
  CHANGELOG.md
  doc/manuals_3.txt
  src/conn.c
  src/include/librpma.h
  src/librpma.map
  tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c
  tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-completion_get.c
  tests/unit/conn/conn-completion_wait.c
  tests/unit/conn/conn-get_completion_fd.c
Labels: sprint goal

#1538 rpma: re-mark enum rpma_op as deprecated
  src/include/librpma.h
Labels: sprint goal, bug fix

#1533 examples: fix example 07
  examples/07-atomic-write/client.c
Labels: sprint goal, bug fix

#1539 rpma: replace rpma_cq_get_completion() with rpma_cq_get_wc()
  src/include/librpma.h
Labels: sprint goal

#1528 examples: add the example_12 receive_completion_queue
  examples/12-receive-completion-queue/CMakeLists.txt
  examples/12-receive-completion-queue/README.md
  examples/12-receive-completion-queue/client.c
  examples/12-receive-completion-queue/receive-completion-queue-common.c
  examples/12-receive-completion-queue/receive-completion-queue-common.h
  examples/12-receive-completion-queue/server.c
  examples/CMakeLists.txt
  examples/run-all-on-SoftRoCE.sh
Labels: sprint goal

#1543 common: fix RCQ shortcut in CHANGELOG.md of release v0.10.0
  CHANGELOG.md
Labels: sprint goal

#1541 rpma: make usage of rpma_cq_wait() and rpma_cq_get_wc() more precise
  src/include/librpma.h
Labels: sprint goal

#1540 examples: delete rpma_cq_get_wc() appearing before rpma_cq_wait()
  examples/08-messages-ping-pong/CMakeLists.txt
  examples/08-messages-ping-pong/client.c
  examples/08-messages-ping-pong/messages-ping-pong-common.c
  examples/08-messages-ping-pong/messages-ping-pong-common.h
  examples/08-messages-ping-pong/server.c
  examples/CMakeLists.txt
Labels: sprint goal

#1535 common: CentOS 8 is EOL, remove it
  .github/workflows/nightly.yml
  INSTALL.md
  utils/docker/images/Dockerfile.centos-8
Labels: sprint goal

#1544 common: update CHANGELOG
  CHANGELOG.md
Labels: sprint goal

#1547 common: fix date of release v0.10.0 in CHANGELOG.md
  CHANGELOG.md
Labels: sprint goal, bug fix

#1537 rpma: document default values of struct rpma_conn_cfg
  CHANGELOG.md
  src/include/librpma.h
Labels: sprint goal

#1548 common: 0.11.0-rc1 release
  CHANGELOG.md
  CMakeLists.txt
  src/librpma.map
Labels: sprint goal

#1550 rpma: see you, Jan!
  README.md
Labels: sprint goal

#1551 examples: add -std=gnu99 option to CMAKE_C_FLAGS in 08 example
  examples/08-messages-ping-pong/CMakeLists.txt
Labels: sprint goal, bug fix

#1552 rpma: fix listing default values of struct rpma_conn_cfg
  src/include/librpma.h
Labels: sprint goal, bug fix

#1554 doc: see you, Jan!
  README.md
Labels: documentation, sprint goal

#1553 examples: make sure the word is always null-terminated
  examples/07-atomic-write/client.c
Labels: sprint goal, bug fix

#1555 rpma: update DEPRECATED documentation of struct rpma_completion
  src/include/librpma.h
Labels: sprint goal

#1556 common: fix Arch Linux CI build
  utils/docker/images/Dockerfile.archlinux-latest
Labels: build system, sprint goal, bug fix

#1558 common: update API version in header of manuals in utils/mans_header.md
  utils/mans_header.md
Labels: sprint goal

#1562 common: fix allowing members of group wheel to execute any command
  utils/docker/images/Dockerfile.opensuse-leap-latest
  utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
Labels: sprint goal, bug fix

#1560 common: 0.11.0 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#1564 common: update header of manuals in utils/mans_header.md
  utils/mans_header.md
Labels: sprint goal

#1567 doc: fix headers of manuals of v0.9.0
  manpages/v0.9.0/librpma.7.md
  manpages/v0.9.0/rpma_conn_apply_remote_peer_cfg.3.md
  manpages/v0.9.0/rpma_conn_cfg_delete.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_cq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_rq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_sq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_get_timeout.3.md
  manpages/v0.9.0/rpma_conn_cfg_new.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_cq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_rq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_sq_size.3.md
  manpages/v0.9.0/rpma_conn_cfg_set_timeout.3.md
  manpages/v0.9.0/rpma_conn_completion_get.3.md
  manpages/v0.9.0/rpma_conn_completion_wait.3.md
  manpages/v0.9.0/rpma_conn_delete.3.md
  manpages/v0.9.0/rpma_conn_disconnect.3.md
  manpages/v0.9.0/rpma_conn_get_completion_fd.3.md
  manpages/v0.9.0/rpma_conn_get_event_fd.3.md
  manpages/v0.9.0/rpma_conn_get_private_data.3.md
  manpages/v0.9.0/rpma_conn_next_event.3.md
  manpages/v0.9.0/rpma_conn_req_connect.3.md
  manpages/v0.9.0/rpma_conn_req_delete.3.md
  manpages/v0.9.0/rpma_conn_req_new.3.md
  manpages/v0.9.0/rpma_conn_req_recv.3.md
  manpages/v0.9.0/rpma_ep_get_fd.3.md
  manpages/v0.9.0/rpma_ep_listen.3.md
  manpages/v0.9.0/rpma_ep_next_conn_req.3.md
  manpages/v0.9.0/rpma_ep_shutdown.3.md
  manpages/v0.9.0/rpma_err_2str.3.md
  manpages/v0.9.0/rpma_flush.3.md
  manpages/v0.9.0/rpma_log_get_threshold.3.md
  manpages/v0.9.0/rpma_log_set_function.3.md
  manpages/v0.9.0/rpma_log_set_threshold.3.md
  manpages/v0.9.0/rpma_mr_dereg.3.md
  manpages/v0.9.0/rpma_mr_get_descriptor.3.md
  manpages/v0.9.0/rpma_mr_get_descriptor_size.3.md
  manpages/v0.9.0/rpma_mr_reg.3.md
  manpages/v0.9.0/rpma_mr_remote_delete.3.md
  manpages/v0.9.0/rpma_mr_remote_from_descriptor.3.md
  manpages/v0.9.0/rpma_mr_remote_get_flush_type.3.md
  manpages/v0.9.0/rpma_mr_remote_get_size.3.md
  manpages/v0.9.0/rpma_peer_cfg_delete.3.md
  manpages/v0.9.0/rpma_peer_cfg_from_descriptor.3.md
  manpages/v0.9.0/rpma_peer_cfg_get_descriptor.3.md
  manpages/v0.9.0/rpma_peer_cfg_get_descriptor_size.3.md
  manpages/v0.9.0/rpma_peer_cfg_get_direct_write_to_pmem.3.md
  manpages/v0.9.0/rpma_peer_cfg_new.3.md
  manpages/v0.9.0/rpma_peer_cfg_set_direct_write_to_pmem.3.md
  manpages/v0.9.0/rpma_peer_delete.3.md
  manpages/v0.9.0/rpma_peer_new.3.md
  manpages/v0.9.0/rpma_read.3.md
  manpages/v0.9.0/rpma_recv.3.md
  manpages/v0.9.0/rpma_send.3.md
  manpages/v0.9.0/rpma_utils_conn_event_2str.3.md
  manpages/v0.9.0/rpma_utils_get_ibv_context.3.md
  manpages/v0.9.0/rpma_utils_ibv_context_is_odp_capable.3.md
  manpages/v0.9.0/rpma_write.3.md
  manpages/v0.9.0/rpma_write_atomic.3.md
Labels: documentation

#1568 doc: examples 07 and 08 were fixed in v0.11.0
  CHANGELOG.md
Labels: documentation, sprint goal

#1569 rpma: prevent a link from being corrupted by txt2man
  src/include/librpma.h
Labels: documentation, sprint goal

#1570 doc: fix links to the article
  manpages/v0.10.0/librpma.7.md
  manpages/v0.11.0/librpma.7.md
  manpages/v0.9.0/librpma.7.md
Labels: documentation, sprint goal, bug fix

#1575 common: update manuals header to the hugo format
  utils/mans_header.md
  utils/src2mans.sh
Labels: documentation, build system, inter-sprint

#1580 common: move temporarily Arch Linux build to Nightly Experimental
  .github/workflows/nightly.yml
  .github/workflows/nightly_experimental.yml
Labels: sprint goal

#1574 common: add automatic update of man pages in the pmem.github.io repo
  utils/docker/build.sh
  utils/docker/run-doc-update.sh
  utils/docker/valid-branches.sh
Labels: enhancement, build system, sprint goal

#1578 rpma: remove deprecated completions API
  CHANGELOG.md
  doc/manuals_3.txt
  src/cq.c
  src/include/librpma.h
  src/librpma.map
  tests/unit/common/mocks-rpma-cq.c
  tests/unit/common/mocks-rpma-cq.h
  tests/unit/cq/CMakeLists.txt
  tests/unit/cq/cq-get_completion.c
Labels: sprint goal

#1579 common: 0.12.0-rc1 release
  CHANGELOG.md
  CMakeLists.txt
  src/librpma.map
  utils/mans_header.md
Labels: sprint goal

#1585 common: fix run-doc-update.sh for builds from a tag
  utils/docker/run-doc-update.sh
Labels: sprint goal, bug fix

#1586 doc: fix links to pmem.io in the pdf file
  reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf
Labels: sprint goal

#1589 tools: add filename_format to templates
  CHANGELOG.md
  tools/perf/templates/part_cpuload.json
  tools/perf/templates/part_mix.json
  tools/perf/templates/part_read.json
  tools/perf/templates/part_write.json
Labels: sprint goal

#1588 common: 0.12.0-rc2 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#1592 common: 0.12.0 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#1590 rpma: ibv_context naming unification
  examples/01-connection/client.c
  examples/01-connection/server.c
  examples/common/common-conn.c
  src/cq.c
  src/cq.h
  src/include/librpma.h
  src/rpma.c
  tests/integration/common/mocks.c
  tests/integration/common/mocks.h
  tests/multithreaded/conn/rpma_conn_get_private_data.c
  tests/multithreaded/conn/rpma_conn_req_new.c
  tests/multithreaded/conn/server_rpma_conn_get_private_data.c
  tests/multithreaded/ep/rpma_ep_get_fd.c
  tests/multithreaded/ep/rpma_ep_listen.c
  tests/multithreaded/mr/rpma_mr_get_descriptor.c
  tests/multithreaded/mr/rpma_mr_get_ptr.c
  tests/multithreaded/mr/rpma_mr_get_size.c
  tests/multithreaded/mr/rpma_mr_reg.c
  tests/multithreaded/peer/rpma_peer_new.c
  tests/multithreaded/utils/rpma_utils_get_ibv_context.c
  tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c
  tests/unit/common/mocks-ibverbs.c
  tests/unit/common/mocks-ibverbs.h
  tests/unit/common/mocks-rpma-cq.c
  tests/unit/common/mocks-rpma-utils.c
  tests/unit/utils/utils-get_ibv_context.c
  tests/unit/utils/utils-ibv_context_is_odp_capable.c
Labels: inter-sprint

#1594 rpma: scaffolding for rpma_atomic_write()
  doc/manuals_3.txt
  src/conn.c
  src/include/librpma.h
  src/librpma.map
  src/mr.c
  src/mr.h
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-atomic_write.c
Labels: sprint goal

#1596 tools: fix part_write.json
  CHANGELOG.md
  tools/perf/templates/part_write.json
Labels: sprint goal, bug fix
