Repository pmem/rpma, pull requests merged in 2022-07, with the labels that each got.

#1911 doc: unify shell command folder
  CONTRIBUTING.md
  INSTALL.md
  tools/perf/BENCHMARKING.md
Labels: sprint goal

#1912 common: remove -dbgsym pkgs from CircleCI environment
  .circleci/install-pkgs-ubuntu.sh
  tests/drd.supp
Labels: sprint goal

#1915 test: add rpma_peer_cfg_set_direct_write_to_pmem MT test
  CHANGELOG.md
  tests/multithreaded/peer/CMakeLists.txt
  tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c
Labels: sprint goal

#1919 test: improve rpma_peer_cfg_set... MT test
  tests/drd.supp
  tests/helgrind.supp
  tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c
Labels: sprint goal

#1917 rpma: make peer_cfg thread-safe
  CHANGELOG.md
  src/peer_cfg.c
  tests/drd.supp
  tests/helgrind.supp
Labels: sprint goal

#1913 rpma: make conn_cfg ... thread safe
  CHANGELOG.md
  THREAD_SAFETY.md
  src/conn_cfg.c
  tests/drd.supp
  tests/helgrind.supp
  tests/multithreaded/conn_cfg/CMakeLists.txt
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common_get.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_cq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rcq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_sq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_timeout.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_cq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_rcq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_rq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c
Labels: sprint goal

#1916 common: organize Dockerfile.Ubuntu-22.04
  utils/docker/images/Dockerfile.ubuntu-22.04
Labels: sprint goal

#1906 rpma: remove unused RPMA_INTEGRATION_TEST
  examples/common/common-hello.c
  examples/common/hello.h
Labels: inter-sprint

#1921 doc: add Dockerfiles references to documentations
  DEVELOPMENT.md
  INSTALL.md
  tools/perf/BENCHMARKING.md
Labels: sprint goal

#1909 examples: add common-pmem_map_file and signature_check to example09
  examples/03-read-to-persistent/CMakeLists.txt
  examples/04-write-to-persistent/CMakeLists.txt
  examples/05-flush-to-persistent/CMakeLists.txt
  examples/09-flush-to-persistent-GPSPM/CMakeLists.txt
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/CMakeLists.txt
  examples/cmake/common.cmake
Labels: sprint goal

#1926 examples: remove redundant src from Cmakelist example09
  examples/09-flush-to-persistent-GPSPM/CMakeLists.txt
Labels: sprint goal

#1929 test: check if result is NULL in MTT_RPMA_ERR()
  tests/multithreaded/common/mtt.h
Labels: sprint goal

#1933 test: postpone starting the child process in MT tests
  tests/multithreaded/common/mtt.c
  tests/multithreaded/common/mtt.h
Labels: sprint goal

#1928 test: add MT test for rpma_ep_next_conn_req()
  CHANGELOG.md
  tests/multithreaded/ep/CMakeLists.txt
  tests/multithreaded/ep/client_rpma_ep_next_conn_req.c
  tests/multithreaded/ep/rpma_ep_next_conn_req.c
Labels: sprint goal

#1931 test: add MT test for rpma_conn_req_connect()
  CHANGELOG.md
  tests/multithreaded/common/mtt_client_process.c
  tests/multithreaded/conn/CMakeLists.txt
  tests/multithreaded/conn/rpma_conn_req_connect.c
  tests/multithreaded/ep/CMakeLists.txt
Labels: sprint goal

#1939 test: fix error messages in mtt_client_connect()
  tests/multithreaded/common/mtt_connect.c
Labels: sprint goal

#1930 rpma: replace PID with TID in logs
  src/log_default.c
  tests/unit/common/mocks-getpid.c
  tests/unit/common/mocks-getpid.h
  tests/unit/common/mocks-glibc.c
  tests/unit/common/mocks-glibc.h
  tests/unit/log_default/CMakeLists.txt
  tests/unit/log_default/function.c
Labels: sprint goal

#1905 common: disable rpma_mr_advise() if IBV_ADVISE_MR flags are not supported
  CMakeLists.txt
  cmake/functions.cmake
  examples/03-read-to-persistent/CMakeLists.txt
  examples/03-read-to-persistent/server.c
  examples/04-write-to-persistent/CMakeLists.txt
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/CMakeLists.txt
  examples/05-flush-to-persistent/server.c
  examples/07-atomic-write/CMakeLists.txt
  examples/07-atomic-write/server.c
  examples/09-flush-to-persistent-GPSPM/CMakeLists.txt
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/09s-flush-to-persistent-GPSPM/CMakeLists.txt
  examples/09s-flush-to-persistent-GPSPM/server.c
  examples/CMakeLists.txt
  examples/cmake/common.cmake
  src/CMakeLists.txt
Labels: inter-sprint

#1947 rpma: fix a comment of Rpma_log_function
  src/log.c
Labels: sprint goal

#1948 rpma: use rpma_log_get_threshold() in rpma_log_set_threshold() (fix)
  src/log.c
Labels: sprint goal, bug fix

#1949 rpma: add missing _Atomic declarations (fix)
  src/conn_cfg.c
Labels: sprint goal, bug fix

#1950 rpma: fix checking if atomic operations are supported
  CMakeLists.txt
  cmake/functions.cmake
  src/conn_cfg.c
  src/peer_cfg.c
Labels: sprint goal, bug fix

#1946 rpma: add the rpma_log_set_function mtt test
  CHANGELOG.md
  tests/multithreaded/CMakeLists.txt
  tests/multithreaded/log/CMakeLists.txt
  tests/multithreaded/log/rpma_log_set_function.c
Labels: sprint goal

#1952 test: add a suppression for a memory leak in pthread_create()
  tests/memcheck-libibverbs-librdmacm.supp
Labels: sprint goal

#1953 rpma: fix atomic operations for Debian 10 with clang
  src/conn_cfg.c
  src/peer_cfg.c
Labels: sprint goal, bug fix

#1923 doc: document rpma_log_default_func()
  THREAD_SAFETY.md
Labels: sprint goal

#1879 tools: add file multiply_connection_benchmark.md
  tools/perf/multiply_connection_benchmark.md
Labels: inter-sprint

#1951 rpma: make rpma_log_set_threshold() thread-safe
  CHANGELOG.md
  src/log.c
  src/log_internal.h
  tests/multithreaded/log/CMakeLists.txt
  tests/multithreaded/log/rpma_log_set_threshold.c
  tests/unit/common/mocks-rpma-log.c
Labels: sprint goal

#1954 test: add a rpma_log_set_get_threshold MT test
  CHANGELOG.md
  tests/multithreaded/log/CMakeLists.txt
  tests/multithreaded/log/rpma_log_set_get_threshold.c
Labels: sprint goal

#1956 rpma: make rpma_log_set_function() thread-safe
  src/log.c
  src/log_internal.h
  tests/unit/common/mocks-rpma-log.c
  tests/unit/common/mocks-rpma-log_default.c
Labels: sprint goal

#1957 examples: add common-pmem_map_file to example07
  examples/07-atomic-write/CMakeLists.txt
  examples/07-atomic-write/server.c
Labels: sprint goal

#1959 examples: use USE_PMEM instead of USE_LIBPMEM in examples 09 and 09s
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/09s-flush-to-persistent-GPSPM/server.c
Labels: sprint goal, bug fix

#1960 Revert "examples: fix building examples with libpmem"
  examples/CMakeLists.txt
Labels: sprint goal
