Repository pmem/rpma, pull requests merged in 2022-08, with the labels that each got.

#1961 rpma: improve CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: sprint goal

#1967 examples: fix the client command in README of example 08
  examples/08-messages-ping-pong/README.md
  examples/08-messages-ping-pong/client.c
Labels: sprint goal, bug fix

#1968 rpma: use librpma without any article
  CHANGELOG.md
  src/log_internal.h
Labels: sprint goal

#1969 common: removed EOLed Ubuntu 21.10
  .github/workflows/nightly.yml
  utils/docker/images/Dockerfile.ubuntu-21.10
Labels: sprint goal

#1966 rpma: improve README.md file
  README.md
Labels: sprint goal

#1972 common: set DEBIAN_FRONTEND=noninteractive in CircleCI
  .circleci/install-pkgs-ubuntu.sh
Labels: sprint goal, bug fix

#1970 rpma: improve INSTALL.md file
  INSTALL.md
  tools/perf/BENCHMARKING.md
Labels: sprint goal

#1971 rpma: improve examples/README.md file
  examples/README.md
Labels: sprint goal

#1964 rpma: remove redundant whitespace
  src/conn.c
  src/include/librpma.h
  src/mr.c
  src/mr.h
Labels: sprint goal

#1965 common: add missing packages to Dockerfiles
  utils/docker/images/Dockerfile.centos-7
  utils/docker/images/Dockerfile.centos-stream
  utils/docker/images/Dockerfile.debian-10
  utils/docker/images/Dockerfile.debian-11
  utils/docker/images/Dockerfile.debian-experimental
  utils/docker/images/Dockerfile.debian-stable
  utils/docker/images/Dockerfile.debian-testing
  utils/docker/images/Dockerfile.fedora-32
  utils/docker/images/Dockerfile.fedora-33
  utils/docker/images/Dockerfile.fedora-34
  utils/docker/images/Dockerfile.fedora-rawhide
  utils/docker/images/Dockerfile.opensuse-leap-latest
  utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
  utils/docker/images/Dockerfile.rockylinux-8.4
  utils/docker/images/Dockerfile.ubuntu-20.04
  utils/docker/images/Dockerfile.ubuntu-22.04
  utils/docker/images/Dockerfile.ubuntu-rolling
  utils/docker/images/Dockerfile.vzlinux-latest
Labels: sprint goal

#1974 examples: continue when rpma_cq_get_wc() returns RPMA_E_NO_COMPLETION
  examples/08-messages-ping-pong/messages-ping-pong-common.c
Labels: sprint goal

#1975 rpma: fault injection cannot falsify the results of rpma_cq_get_wc()
  src/cq.c
Labels: sprint goal, bug fix

#1977 examples: move strtoul_noerror() to common-utils
  examples/08-messages-ping-pong/CMakeLists.txt
  examples/08-messages-ping-pong/client.c
  examples/12-receive-completion-queue/CMakeLists.txt
  examples/12-receive-completion-queue/client.c
  examples/12s-receive-completion-queue/CMakeLists.txt
  examples/12s-receive-completion-queue/client.c
  examples/13-messages-ping-pong-with-srq/CMakeLists.txt
  examples/13-messages-ping-pong-with-srq/client.c
  examples/CMakeLists.txt
  examples/common/common-utils.c
  examples/common/common-utils.h
Labels: enhancement, sprint goal

#1979 examples: remove unused file hello.h
  examples/common/hello.h
Labels: sprint goal

#1978 examples: validate a value of timeout in example 13
  examples/13-messages-ping-pong-with-srq/server.c
Labels: sprint goal

#1982 rpma: rpma_conn_cfg_get_timeout() has to return correct value
  src/conn_cfg.c
Labels: sprint goal, bug fix

#1981 examples: add 08srq-simple-messages-ping-pong-with-srq example
  CHANGELOG.md
  examples/08srq-simple-messages-ping-pong-with-srq/CMakeLists.txt
  examples/08srq-simple-messages-ping-pong-with-srq/README.md
  examples/08srq-simple-messages-ping-pong-with-srq/client.c
  examples/08srq-simple-messages-ping-pong-with-srq/server.c
  examples/CMakeLists.txt
  examples/common/common-messages-ping-pong.c
  examples/common/common-messages-ping-pong.h
  examples/run-all-examples.sh
Labels: sprint goal

#1963 rpma: change the names of the internal API functions
  CHANGELOG.md
  src/conn.c
  src/conn_cfg.c
  src/conn_req.c
  src/conn_req.h
  src/ep.c
  src/flush.c
  src/mr.c
  src/peer.c
  src/peer.h
  src/private_data.c
  src/private_data.h
  tests/drd.supp
  tests/memcheck-libibverbs-librdmacm.supp
  tests/unit/common/mocks-ibverbs.c
  tests/unit/common/mocks-rpma-flush.c
  tests/unit/common/mocks-rpma-peer.c
  tests/unit/common/mocks-rpma-peer.h
  tests/unit/common/mocks-rpma-private_data.c
  tests/unit/conn/conn-common.c
  tests/unit/conn/conn-flush.c
  tests/unit/conn/conn-new.c
  tests/unit/conn/conn-next_event.c
  tests/unit/conn_req/CMakeLists.txt
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-common.h
  tests/unit/conn_req/conn_req-connect.c
  tests/unit/conn_req/conn_req-delete.c
  tests/unit/conn_req/conn_req-new.c
  tests/unit/conn_req/conn_req-new_from_cm_event.c
  tests/unit/conn_req/conn_req-private_data.c
  tests/unit/ep/ep-common.c
  tests/unit/ep/ep-next_conn_req.c
  tests/unit/flush/CMakeLists.txt
  tests/unit/flush/flush-apm_execute.c
  tests/unit/mr/mr-common.c
  tests/unit/mr/mr-reg.c
  tests/unit/peer/peer-create_qp.c
  tests/unit/peer/peer-mr_reg.c
  tests/unit/private_data/private_data-common.c
Labels: sprint goal

#1983 examples: rename examples using shared completion channel
  examples/06scch-multiple-connections/CMakeLists.txt
  examples/06scch-multiple-connections/README.md
  examples/06scch-multiple-connections/client.c
  examples/06scch-multiple-connections/multiple-connections-common.h
  examples/06scch-multiple-connections/server.c
  examples/09scch-flush-to-persistent-GPSPM/CMakeLists.txt
  examples/09scch-flush-to-persistent-GPSPM/GPSPM_flush.pb-c.c
  examples/09scch-flush-to-persistent-GPSPM/GPSPM_flush.pb-c.h
  examples/09scch-flush-to-persistent-GPSPM/GPSPM_flush.proto
  examples/09scch-flush-to-persistent-GPSPM/README.md
  examples/09scch-flush-to-persistent-GPSPM/client.c
  examples/09scch-flush-to-persistent-GPSPM/flush-to-persistent-GPSPM.h
  examples/09scch-flush-to-persistent-GPSPM/server.c
  examples/12scch-receive-completion-queue/CMakeLists.txt
  examples/12scch-receive-completion-queue/README.md
  examples/12scch-receive-completion-queue/client.c
  examples/12scch-receive-completion-queue/receive-completion-queue-common.h
  examples/12scch-receive-completion-queue/server.c
  examples/CMakeLists.txt
  examples/run-all-examples.sh
  utils/docker/run-build.sh
Labels: sprint goal

#1984 examples: make all examples comply the new chars line limit
  examples/01-connection/client.c
  examples/01-connection/server.c
  examples/02-read-to-volatile/client.c
  examples/02-read-to-volatile/server.c
  examples/06-multiple-connections/client.c
  examples/06-multiple-connections/server.c
  examples/06scch-multiple-connections/client.c
  examples/06scch-multiple-connections/server.c
  examples/07-atomic-write/client.c
  examples/07-atomic-write/server.c
  examples/08-messages-ping-pong/client.c
  examples/08-messages-ping-pong/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/09scch-flush-to-persistent-GPSPM/client.c
  examples/09scch-flush-to-persistent-GPSPM/server.c
  examples/10-send-with-imm/client.c
  examples/10-send-with-imm/server.c
  examples/11-write-with-imm/client.c
  examples/11-write-with-imm/server.c
  examples/12-receive-completion-queue/client.c
  examples/12-receive-completion-queue/server.c
  examples/12scch-receive-completion-queue/client.c
  examples/12scch-receive-completion-queue/server.c
Labels: sprint goal

#1955 test: add rpma_conn_cfg_get/set_srq MT tests
  CHANGELOG.md
  THREAD_SAFETY.md
  tests/multithreaded/conn_cfg/CMakeLists.txt
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_srq.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_srq.c
Labels: sprint goal

#1987 examples: make the internal API comply the new chars line limit
  CHANGELOG.md
  src/conn.c
  src/conn.h
  src/conn_cfg.c
  src/conn_req.c
  src/conn_req.h
  src/ep.c
  src/flush.c
  src/mr.c
  src/mr.h
  src/peer.c
  src/peer.h
  src/private_data.c
  src/private_data.h
Labels: sprint goal

#1988 rpma: fix fault injection in rpma_srq_cfg_delete()
  src/srq_cfg.c
Labels: sprint goal, bug fix

#1958 test: add rpma_srq_cfg MT tests
  CHANGELOG.md
  tests/multithreaded/CMakeLists.txt
  tests/multithreaded/srq_cfg/CMakeLists.txt
  tests/multithreaded/srq_cfg/rpma_srq_cfg_common.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_common.h
  tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rcq_size.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rq_size.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rq_size.c
Labels: sprint goal

#1985 examples: expand 08srq-simple-messages-ping-pong-with-srq
  examples/08srq-simple-messages-ping-pong-with-srq/README.md
  examples/08srq-simple-messages-ping-pong-with-srq/server.c
Labels: sprint goal

#1989 common: fix a command in the DEVELOPMENT.md file
  DEVELOPMENT.md
Labels: sprint goal, bug fix

#1990 common: 1.0.0-rc1 release
  CHANGELOG.md
  CMakeLists.txt
  src/librpma.map
  utils/mans_header.md
Labels: sprint goal

#1991 common: set version of docker images to 'devel' for the devel branch
  utils/docker/images/set-images-version.sh
Labels: sprint goal, bug fix

#1996 doc: fix bolding Direct Write to PMem
  src/include/librpma.h
Labels: sprint goal, bug fix

#1998 common: replace \fP with \fR in groff manuals
  utils/src2mans.sh
Labels: sprint goal, bug fix

#1999 examples: fix running example 08srq
  examples/run-all-examples.sh
Labels: sprint goal, bug fix

#1997 common: 1.0.0-rc2 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#2001 test: remove unused functions from cmocka_headers.h
  tests/cmocka_headers.h
Labels: sprint goal

#2002 common: remove unused md2man files
  utils/md2man/default.man
  utils/md2man/md2man.sh
Labels: sprint goal

#2003 common: remove unused libunwind and test_backtrace
  tests/CMakeLists.txt
  tests/cmake/ctest_helpers.cmake
  tests/cmake/helpers.cmake
  tests/memcheck-libunwind.supp
  tests/test_backtrace.c
  tests/test_backtrace.h
  utils/docker/images/Dockerfile.archlinux-latest
  utils/docker/images/Dockerfile.centos-7
  utils/docker/images/Dockerfile.centos-stream
  utils/docker/images/Dockerfile.debian-10
  utils/docker/images/Dockerfile.debian-11
  utils/docker/images/Dockerfile.debian-experimental
  utils/docker/images/Dockerfile.debian-stable
  utils/docker/images/Dockerfile.debian-testing
  utils/docker/images/Dockerfile.fedora-32
  utils/docker/images/Dockerfile.fedora-33
  utils/docker/images/Dockerfile.fedora-34
  utils/docker/images/Dockerfile.fedora-rawhide
  utils/docker/images/Dockerfile.opensuse-leap-latest
  utils/docker/images/Dockerfile.opensuse-tumbleweed-latest
  utils/docker/images/Dockerfile.rockylinux-8.4
  utils/docker/images/Dockerfile.ubuntu-20.04
  utils/docker/images/Dockerfile.ubuntu-22.04
  utils/docker/images/Dockerfile.ubuntu-rolling
  utils/docker/images/Dockerfile.vzlinux-latest
Labels: sprint goal

#2004 common: 1.0.0-rc3 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#2007 common: make sure WORKDIR has correct permissions
  utils/docker/prepare-for-build.sh
Labels: sprint goal

#2000 common: 1.0.0 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal
