Repository pmem/rpma, pull requests merged in 2022-03, with the labels that each got.

#1598 rpma: finish the documentation for rpma_atomic_write()
  src/include/librpma.h
  src/mr.h
Labels: documentation, sprint goal

#1602 rpma: fix indentations in enum rpma_conn_event
  src/include/librpma.h
Labels: sprint goal

#1605 rpma: fix documentation of rpma_utils_conn_event_2str()
  CHANGELOG.md
  src/include/librpma.h
Labels: documentation, sprint goal, bug fix

#1601 rpma: implement rpma_atomic_write()
  CHANGELOG.md
  src/conn.c
  src/mr.c
  src/peer.c
  tests/integration/common/mocks.h
  tests/unit/common/mocks-rpma-conn_cfg.h
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/conn/conn-atomic_write.c
  tests/unit/mr/CMakeLists.txt
  tests/unit/mr/mr-atomic_write.c
Labels: sprint goal

#1608 rpma: mark rpma_write_atomic() as deprecated
  CHANGELOG.md
  src/include/librpma.h
Labels: sprint goal

#1607 examples: replace rpma_write_atomic() with rpma_atomic_write()
  CHANGELOG.md
  examples/07-atomic-write/client.c
Labels: sprint goal

#1609 common: 0.13.0-rc1 release
  CHANGELOG.md
  CMakeLists.txt
  src/librpma.map
  utils/mans_header.md
Labels: sprint goal

#1612 examples: set the return value if an error occurs
  examples/07-atomic-write/client.c
Labels: sprint goal, bug fix

#1611 common: 0.13.0 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#1617 rpma: fix rpma_log_init() and log's unit test
  CHANGELOG.md
  src/log.c
  tests/unit/common/mocks-rpma-log_default.c
  tests/unit/log/CMakeLists.txt
  tests/unit/log/macros.c
  tests/unit/log/threshold.c
Labels: sprint goal, bug fix

#1606 rpma: add RPMA_CONN_UNREACHABLE to handle RDMA_CM_EVENT_UNREACHABLE
  CHANGELOG.md
  src/conn.c
  src/include/librpma.h
  src/rpma.c
  tests/unit/conn/conn-next_event.c
  tests/unit/utils/utils-conn_event_2str.c
Labels: sprint goal

#1618 rpma: remove rpma_write_atomic()
  CHANGELOG.md
  doc/manuals_3.txt
  src/conn.c
  src/include/librpma.h
  src/librpma.map
  src/mr.c
  src/mr.h
  tests/unit/common/mocks-rpma-mr.c
  tests/unit/common/test-common.h
  tests/unit/conn/CMakeLists.txt
  tests/unit/conn/conn-write.c
  tests/unit/conn/conn-write_atomic.c
  tests/unit/conn/conn-write_with_imm.c
  tests/unit/mr/mr-write.c
Labels: sprint goal

#1623 common: 0.14.0 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#1622 reports: CLX + MLX + CentOS 8.4 + FSDAX
  reports/RPMA_Perf_report_CLX_MLX_CentOS8.2.pdf
  reports/index.md
Labels: sprint goal

#1626 doc: update perf-tuning.md for ICX
  documentation/perf-tuning.md
Labels: sprint goal

#1604 test: fix and enable the rpma_conn_get_private_data MT test
  tests/multithreaded/conn/CMakeLists.txt
  tests/multithreaded/conn/rpma_conn_get_private_data.c
Labels: sprint goal

#1629 doc: update perf-tuning.md for ICX
  documentation/perf-tuning.md
Labels: sprint goal

#1634 rpma: log GID addresses in rpma_conn_req_from_id()
  CHANGELOG.md
  src/conn_req.c
  tests/unit/common/mocks-rdma_cm.c
  tests/unit/common/mocks-rdma_cm.h
  tests/unit/common/mocks-rpma-log.c
  tests/unit/conn_req/CMakeLists.txt
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-common.h
  tests/unit/conn_req/conn_req-from_cm_event.c
Labels: sprint goal
