Repository pmem/rpma, pull requests merged in 2022-05, with the labels that each got.

#1718 examples: add a readme to the example15
  examples/15-multiple-connections-SHCCH/README.md
Labels: sprint goal

#1721 test: fix coding style in MT tests
  tests/multithreaded/conn/rpma_conn_get_private_data.c
  tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
Labels: sprint goal

#1712 example: add example 15
  examples/15-multiple-connections-SHCCH/client.c
  examples/15-multiple-connections-SHCCH/server.c
Labels: sprint goal

#1717 test: add one rpma_read and two rpma_write MT tests
  tests/multithreaded/conn/CMakeLists.txt
  tests/multithreaded/conn/rpma_common.c
  tests/multithreaded/conn/rpma_common.h
  tests/multithreaded/conn/rpma_read.c
  tests/multithreaded/conn/rpma_write.c
  tests/multithreaded/conn/rpma_write_read.c
  tests/multithreaded/conn/server_rpma_common.c
  tests/multithreaded/conn/server_rpma_common.h
  tests/multithreaded/conn/server_rpma_empty.c
  tests/multithreaded/run_group.cmake
Labels: sprint goal

#1719 test: add rpma_send MT test
  tests/multithreaded/conn/CMakeLists.txt
  tests/multithreaded/conn/rpma_common.c
  tests/multithreaded/conn/rpma_common.h
  tests/multithreaded/conn/rpma_read.c
  tests/multithreaded/conn/rpma_send.c
  tests/multithreaded/conn/rpma_write_read.c
  tests/multithreaded/conn/server_rpma_common.c
  tests/multithreaded/conn/server_rpma_send.c
Labels: sprint goal

#1631 examples: add libpmem2 to example 03
  examples/03-read-to-persistent/CMakeLists.txt
  examples/03-read-to-persistent/client.c
  examples/CMakeLists.txt
  examples/common/common-conn.h
  examples/common/common-pmem.h
  examples/common/common-pmem2_map_file.c
  examples/common/common-pmem_map_file.c
  examples/common/common-pmem_map_file.h
Labels: inter-sprint

#1723 examples: add functions to start commands in run-all-on-SoftRoCE.sh
  examples/run-all-on-SoftRoCE.sh
Labels: sprint goal

#1726 rpma: add missing rpma_private_data_discard() to rpma_conn_req_accept()
  src/conn_req.c
  tests/unit/conn_req/conn_req-connect.c
Labels: sprint goal, bug fix

#1727 rpma: fix memory leak in error handling of rpma_conn_req_connect()
  src/conn_req.c
  tests/unit/conn_req/conn_req-connect.c
Labels: sprint goal, bug fix

#1724 common: fix usage of sudo_password
  utils/docker/run-build.sh
Labels: bug fix

#1703 rpma: ack the connection request event in rpma_ep_next_conn_req()
  src/conn_req.c
  src/ep.c
  tests/unit/conn_req/conn_req-common.c
  tests/unit/conn_req/conn_req-connect.c
  tests/unit/conn_req/conn_req-delete.c
  tests/unit/conn_req/conn_req-from_cm_event.c
  tests/unit/conn_req/conn_req-private_data.c
  tests/unit/ep/ep-common.c
  tests/unit/ep/ep-next_conn_req.c
Labels: sprint goal

#1647 rpma: add fault injection and debug tracing
  CMakeLists.txt
  INSTALL.md
  src/CMakeLists.txt
  src/conn.c
  src/conn_cfg.c
  src/conn_req.c
  src/cq.c
  src/debug.c
  src/debug.h
  src/ep.c
  src/flush.c
  src/include/librpma.h
  src/info.c
  src/mr.c
  src/peer.c
  src/peer_cfg.c
  src/private_data.c
  src/rpma.c
  src/rpma_err.c
  tests/unit/error/error.c
Labels: sprint goal

#1729 test: fix memory leaks for rpma_mr_remote_from_descriptor
  tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
Labels: inter-sprint

#1730 rpma: move common code into rpma_conn_req_delete()
  src/conn_req.c
Labels: sprint goal

#1731 examples: fix memory leak in example 04
  examples/04-write-to-persistent/client.c
Labels: sprint goal

#1733 rpma: fix memory leak in rpma_ep_shutdown()
  src/ep.c
  tests/unit/ep/ep-listen.c
Labels: sprint goal, bug fix

#1735 rpma: simplify fault injection in rpma_conn_req_accept()
  src/conn_req.c
Labels: sprint goal

#1738 examples: fix memory leak in example 08
  examples/08-messages-ping-pong/server.c
Labels: sprint goal, bug fix

#1739 examples: fix error handling in example 08
  examples/08-messages-ping-pong/messages-ping-pong-common.c
Labels: sprint goal, bug fix

#1736 rpma: add fault injection also inside functions
  src/conn.c
  src/conn_cfg.c
  src/conn_req.c
  src/cq.c
  src/debug.c
  src/debug.h
  src/ep.c
  src/flush.c
  src/include/librpma.h
  src/info.c
  src/mr.c
  src/peer.c
  src/peer_cfg.c
  src/private_data.c
  src/rpma.c
  src/rpma_err.c
  tests/unit/error/error.c
Labels: sprint goal

#1741 examples: fix wait_and_process_completions() in example 08
  examples/08-messages-ping-pong/messages-ping-pong-common.c
Labels: sprint goal, bug fix

#1745 examples: add common-pmem2_map_file.c and common-pmem2_map_file.c
  examples/CMakeLists.txt
Labels: inter-sprint

#1751 rpma: scaffolding of thread safety analysis of the librpma library
  THREAD_SAFETY.md
Labels: sprint goal

#1755 rpma: add main assumptions of the analysis of thread safety
  THREAD_SAFETY.md
Labels: sprint goal

#1758 rpma: move description of thread safety to THREAD_SAFETY.md
  THREAD_SAFETY.md
  src/include/librpma.h
Labels: sprint goal

#1756 rpma: analysis of thread safety (peer + peer_cfg)
  THREAD_SAFETY.md
  src/peer_cfg.c
Labels: sprint goal

#1757 rpma: analysis of thread safety: rpma_conn_cfg_
  THREAD_SAFETY.md
Labels: sprint goal

#1759 rpma: analysis of thread safety: rpma_conn_req_
  THREAD_SAFETY.md
Labels: sprint goal

#1763 rpma: analysis of thread safety: rpma_mr_
  THREAD_SAFETY.md
Labels: sprint goal

#1761 rpma: analysis of thread safety: rpma_ep_
  THREAD_SAFETY.md
Labels: sprint goal

#1760 rpma: analysis of thread safety: rpma_conn_
  THREAD_SAFETY.md
Labels: sprint goal

#1764 rpma: analysis of thread safety: rpma_cq_
  THREAD_SAFETY.md
Labels: sprint goal

#1765 rpma: analysis of thread safety: rpma.c
  THREAD_SAFETY.md
Labels: sprint goal

#1770 rpma: analysis of thread safety: rpma_err_2str
  THREAD_SAFETY.md
  src/rpma_err.c
Labels: sprint goal

#1774 rpma: only one librpma API call is not thread-safe
  THREAD_SAFETY.md
Labels: sprint goal

#1772 rpma: analysis of thread safety: rpma_log_
  THREAD_SAFETY.md
Labels: sprint goal

#1780 common: doc update should be run only on the master branch (fix)
  utils/docker/build.sh
Labels: documentation, build system, bug fix

#1782 common: set WORKDIR as a safe directory
  utils/docker/prepare-for-build.sh
Labels: build system, bug fix

#1786 common: set WORKDIR as a safe directory
  utils/docker/prepare-for-build.sh
Labels: bug fix

#1785 rpma: the main assumptions must be met
  THREAD_SAFETY.md
Labels: sprint goal

#1787 common: add Ubuntu 22.04 to CI and remove EOLed 21.04
  .github/workflows/nightly.yml
  .github/workflows/on_pull_request.yml
  utils/docker/images/Dockerfile.ubuntu-22.04
Labels: build system, sprint goal

#1793 common: add --allow-unauthenticated to apt-get in CircleCI
  .circleci/install-pkgs-ubuntu.sh
Labels: build system, sprint goal, bug fix

#1788 rpma: relationship of libibverbs and librdmacm
  THREAD_SAFETY.md
Labels: sprint goal
