Repository pmem/rpma, pull requests merged in 2022-09, with the labels that each got.

#2011 rpma: standardize the if condition in the mr.c file
  src/mr.c
Labels: inter-sprint

#2010 examples: remove unnecessary rpma_conn_req_delete()
  examples/01-connection/client.c
  examples/01-connection/server.c
  examples/06-multiple-connections/server.c
  examples/06scch-multiple-connections/server.c
  examples/08-messages-ping-pong/server.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/09scch-flush-to-persistent-GPSPM/server.c
  examples/10-send-with-imm/server.c
  examples/11-write-with-imm/server.c
  examples/common/common-conn.c
Labels: inter-sprint

#2013 common: update CHANGELOG.md
  CHANGELOG.md
Labels: sprint goal

#2014 test: standardize the code style in test files
  CHANGELOG.md
  tests/multithreaded/common/mtt.c
  tests/multithreaded/common/mtt_connect.c
  tests/multithreaded/conn/rpma_conn_common.c
  tests/multithreaded/conn/rpma_conn_req_delete.c
  tests/multithreaded/conn/rpma_conn_req_new.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_cq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rcq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_sq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_srq.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_get_timeout.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_new.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_cq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_rcq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_rq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_srq.c
  tests/multithreaded/conn_cfg/rpma_conn_cfg_set_timeout.c
  tests/multithreaded/ep/rpma_ep_get_fd.c
  tests/multithreaded/ep/rpma_ep_listen.c
  tests/multithreaded/ep/rpma_ep_shutdown.c
  tests/multithreaded/log/rpma_log_set_function.c
  tests/multithreaded/log/rpma_log_set_get_threshold.c
  tests/multithreaded/log/rpma_log_set_threshold.c
  tests/multithreaded/mr/rpma_mr_dereg.c
  tests/multithreaded/mr/rpma_mr_get_descriptor.c
  tests/multithreaded/mr/rpma_mr_get_ptr.c
  tests/multithreaded/mr/rpma_mr_get_size.c
  tests/multithreaded/mr/rpma_mr_reg.c
  tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c
  tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c
  tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c
  tests/multithreaded/peer/rpma_peer_new.c
  tests/multithreaded/srq/rpma_srq_delete.c
  tests/multithreaded/srq/rpma_srq_get_rcq.c
  tests/multithreaded/srq/rpma_srq_new.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_common.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rcq_size.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rq_size.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c
  tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rq_size.c
Labels: inter-sprint

#2016 examples: change the write size from KILOBYTE to HELLO_STR_SIZE
  CHANGELOG.md
  examples/04-write-to-persistent/client.c
  examples/04-write-to-persistent/server.c
  examples/05-flush-to-persistent/client.c
  examples/05-flush-to-persistent/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/09scch-flush-to-persistent-GPSPM/client.c
  examples/09scch-flush-to-persistent-GPSPM/server.c
Labels: inter-sprint

#2015 examples: standardize the code style in example files
  CHANGELOG.md
  examples/07-atomic-write/client.c
  examples/07-atomic-write/server.c
  examples/08-messages-ping-pong/client.c
  examples/08-messages-ping-pong/server.c
  examples/08srq-simple-messages-ping-pong-with-srq/client.c
  examples/08srq-simple-messages-ping-pong-with-srq/server.c
  examples/09-flush-to-persistent-GPSPM/client.c
  examples/09-flush-to-persistent-GPSPM/server.c
  examples/09scch-flush-to-persistent-GPSPM/client.c
  examples/09scch-flush-to-persistent-GPSPM/server.c
  examples/10-send-with-imm/server.c
  examples/11-write-with-imm/server.c
  examples/12-receive-completion-queue/client.c
  examples/12-receive-completion-queue/receive-completion-queue-common.c
  examples/12-receive-completion-queue/server.c
  examples/12scch-receive-completion-queue/client.c
  examples/12scch-receive-completion-queue/server.c
  examples/13-messages-ping-pong-with-srq/client.c
  examples/13-messages-ping-pong-with-srq/server.c
  examples/common/common-conn.c
  examples/common/common-messages-ping-pong.c
Labels: inter-sprint

#2020 common: 1.1.0-rc1 release
  CHANGELOG.md
  CMakeLists.txt
  src/librpma.map
  utils/mans_header.md
Labels: sprint goal

#2018 test: standardize the code style in test files
  tests/multithreaded/common/mtt.c
  tests/multithreaded/peer/rpma_peer_cfg_new.c
  tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c
Labels: inter-sprint

#2022 common: 1.1.0-rc2 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#2023 common: 1.1.0 release
  CHANGELOG.md
  CMakeLists.txt
Labels: sprint goal

#2025 rpma: fix ABI version from 1.1 to 1.0
  src/librpma.map
Labels: sprint goal, bug fix

#2028 doc: running tests requires CMAKE_BUILD_TYPE set to Debug
  DEVELOPMENT.md
Labels: documentation, bug fix

#2029 common: install python3-devel in Fedora Rawhide (fix)
  CHANGELOG.md
  utils/docker/images/Dockerfile.fedora-rawhide
Labels: build system, bug fix

#2034 common: use cmake3 if cmake is v2.x
  CHANGELOG.md
  utils/docker/run-build.sh
Labels: build system
